// =====================================================================
//  MOTS FLÉCHÉS — deuxième extension du dictionnaire.
//
//  Pourquoi ce fichier : le stock ne suivait pas la consommation. Trois
//  grilles par jour mangent une cinquantaine de mots ; la règle « pas de
//  mot revu avant quinze jours » avait donc besoin d'au moins trente
//  jours de réserve par longueur, et n'en avait que vingt-trois sur le
//  niveau Moyen. Quand il restait moins de huit mots d'une longueur, la
//  règle sautait en silence — vingt-trois jours sur trente pour les mots
//  de trois lettres, qui font justement la majorité des grilles.
//
//  ⚠️ Le trou le plus grave était les TROIS LETTRES : `words-extra.js`
//  n'en contenait aucun, et le dictionnaire de base n'en avait que 82.
//  C'est la longueur la plus sollicitée par le générateur (elle se case
//  partout), donc celle qui s'épuise en premier.
//
//  Format identique aux deux autres fichiers :
//     ['MOT', 'définition 1|définition 2', niveau]
//     niveau 1 = courant · 2 = moins courant · 3 = rare / expert
//  Sans accent, en MAJUSCULES, A-Z uniquement.
//
//  Règle de rédaction : une définition ne doit JAMAIS contenir sa propre
//  réponse, ni un mot de la même famille (« JOUR → Journée » n'est pas
//  une définition, c'est un cadeau).
// =====================================================================

const Y3 = [
['ACE', 'Service gagnant au tennis|Balle imparable', 2],
['AIE', 'Cri de douleur|On le dit en se pinçant', 2],
['ALE', 'Bière anglaise|Blonde d’outre-Manche', 3],
['ARA', 'Perroquet coloré|Oiseau d’Amazonie', 2],
['AVE', 'Prière à Marie|Salutation latine', 3],
['AXE', 'Ligne de symétrie|Grande direction|Il traverse la roue', 1],
['BAI', 'Robe brune du cheval|Couleur de monture', 3],
['BAR', 'On y prend un verre|Comptoir|Poisson de mer', 1],
['BAS', 'Le contraire du haut|Il monte sur la jambe', 1],
['BAT', 'Charge portée par l’âne|Il blesse la bête de somme', 3],
['BEE', 'Bouche grande ouverte|Rester ainsi, ébahi', 3],
['BIS', 'On le crie après le concert|Une seconde fois', 2],
['BLE', 'Céréale du pain|Il dore en juillet', 1],
['BOA', 'Serpent qui étouffe|Écharpe de plumes', 2],
['BON', 'Agréable au palais|Coupon de réduction', 1],
['BRU', 'Belle-fille|Épouse du fils', 3],
['CAL', 'Épaississement de la peau|Durillon du travailleur', 3],
['CAS', 'Situation particulière|Il fait jurisprudence', 1],
['CEP', 'Pied de vigne|Il porte les grappes', 3],
['CIL', 'Poil de la paupière|Il protège l’œil', 2],
['COQ', 'Il chante au lever du jour|Roi de la basse-cour', 1],
['COR', 'Instrument de chasse|Durillon du pied', 2],
['COU', 'Il porte la tête|On y met une écharpe', 1],
['DIT', 'Parole rapportée|Récit médiéval', 3],
['DUC', 'Titre de noblesse|Noble juste sous le prince', 2],
['DUR', 'Difficile|Le contraire de tendre', 1],
['ELU', 'Il a gagné les élections|Choisi par le vote', 1],
['EMU', 'Touché aux larmes|Gagné par le trouble', 1],
['ERE', 'Longue période|Elle commence une histoire', 2],
['EST', 'Point cardinal|Là où le soleil se lève', 1],
['FAN', 'Admirateur passionné|Il suit son idole', 2],
['FAT', 'Vaniteux ridicule|Plein de suffisance', 3],
['FEE', 'Elle a une baguette|Marraine des contes', 1],
['FOI', 'Croyance profonde|Confiance donnée', 1],
['FOU', 'Il a perdu la raison|Pièce du jeu d’échecs', 1],
['FUT', 'Tonneau de chêne|Tronc sous les branches', 3],
['GAG', 'Il fait rire au cinéma|Trouvaille comique', 2],
['GAI', 'De bonne humeur|Il rit volontiers', 1],
['GIN', 'Alcool au genièvre|Base du cocktail tonic', 2],
['GRE', 'À son bon vouloir|Contre son… , de force', 3],
['GUE', 'Passage à pied dans la rivière|On le traverse sans pont', 3],
['GUI', 'On s’embrasse dessous|Plante du Nouvel An', 2],
['ICI', 'À cet endroit|Le contraire de là-bas', 1],
['IRE', 'Colère, en vieux français|Fureur des poètes', 3],
['JET', 'Lancer vif|Il sort de la fontaine', 1],
['JOB', 'Petit travail|Emploi, familièrement', 2],
['LIN', 'Fibre du drap frais|Sa fleur est bleue', 2],
['LIS', 'Fleur royale|Emblème des rois de France', 2],
['LOT', 'Part d’un partage|Il tombe à la tombola', 1],
['MAS', 'Ferme provençale|Maison du Midi', 3],
['MAT', 'Sans éclat|Fin de partie aux échecs', 2],
['MEC', 'Type, familièrement|Garçon, dans la rue', 2],
['MIL', 'Céréale d’Afrique|Petite graine nourricière', 3],
['MOI', 'Le sujet qui parle|Mon propre personnage', 1],
['MOT', 'Suite de lettres qui a un sens|On le cherche dans la grille', 1],
['MOU', 'Sans fermeté|Le contraire de raide', 1],
['MUE', 'Changement de voix|Le serpent y perd sa peau', 2],
['NEF', 'Grand vaisseau de l’église|Partie centrale du sanctuaire', 3],
['NON', 'Refus net|Le contraire de oui', 1],
['NUE', 'Nuage, en poésie|Porter aux… , encenser', 3],
['PAL', 'Pieu pointu|Bande verticale du blason', 3],
['PAN', 'Morceau de mur|Bruit de la détonation', 2],
['PAT', 'Partie nulle aux échecs|Roi bloqué sans échec', 3],
['PEU', 'Pas beaucoup|Une petite quantité', 1],
['PIS', 'Mamelle de la vache|Tant… , c’est dommage', 2],
['PLI', 'Marque du fer à repasser|Enveloppe de courrier', 2],
['POU', 'Parasite des cheveux|Il fait gratter la tête', 2],
['PRO', 'Il en vit, contrairement à l’amateur|Joueur de métier', 2],
['PUS', 'Il sort de la plaie infectée|Signe d’infection', 3],
['PUY', 'Volcan d’Auvergne|Sommet arrondi', 3],
['RAP', 'Musique scandée|On y pose des rimes', 2],
['RAZ', 'Courant marin violent|… de marée', 3],
['ROC', 'Masse de pierre|Solide comme lui', 2],
['SET', 'Manche au tennis|Napperon individuel', 2],
['SIX', 'Après cinq|Face maximale du dé', 1],
['SKI', 'Planche de neige|Sport des Alpes', 1],
['SOC', 'Lame de la charrue|Il ouvre le sillon', 3],
['SOI', 'Chacun pour… |Le moi intérieur', 2],
['SON', 'Il voyage dans l’air|Enveloppe du grain', 1],
['SOT', 'Dépourvu d’esprit|Bête et content de l’être', 2],
['SUC', 'Liquide de la plante|Il donne la saveur', 3],
['SUD', 'Opposé au nord|Direction du soleil de midi', 1],
['TIC', 'Geste involontaire|Manie qui revient', 2],
['TOC', 'Faux bijou|Bruit contre la porte', 2],
['TOT', 'De bonne heure|Avant l’heure prévue', 1],
['TRI', 'Séparation des déchets|Classement méthodique', 1],
['UNI', 'Sans motif|Rassemblé par un lien', 2],
['USE', 'Fatigué par le temps|Élimé jusqu’à la corde', 2],
['VAL', 'Par monts et par…|Par monts et par…', 3],
['VAN', 'Panier à secouer le grain|Il sépare la balle', 3],
['VIA', 'En passant par|Par l’intermédiaire de', 2],
['VIE', 'De la naissance à la mort|Elle est belle, dit-on', 1],
['VIF', 'Plein d’énergie|Rapide à comprendre', 1],
['ZEN', 'Très calme|Courant du bouddhisme', 2],
];

const Y4 = [
['AMER', 'Goût du café sans sucre|Plein de rancœur', 1],
['AVIS', 'Opinion donnée|Petite annonce officielle', 1],
['BAIL', 'Contrat de location|Il lie le propriétaire', 2],
['BARD', 'Civière à bras|Outil de portage', 3],
['BILE', 'Liquide du foie|Se faire de la…, s’inquiéter', 2],
['BLOC', 'Masse d’un seul tenant|Carnet de feuilles', 1],
['BOUC', 'Mâle de la chèvre|Barbe au menton', 2],
['BRAI', 'Résidu du goudron|Matière noire et collante', 3],
['CADI', 'Juge musulman|Magistrat du Maghreb', 3],
['CALE', 'Fond du navire|Coin qui bloque la roue', 2],
['CAMP', 'Il se monte sous la tente|Chacun défend le sien', 1],
['CHAR', 'Blindé de l’armée|Il défile au carnaval', 1],
['CLAP', 'Il claque avant la prise|Signal du tournage', 3],
['COCU', 'Trompé par sa moitié|Il porte des cornes', 3],
['CRIC', 'Il soulève la voiture|Outil du changement de roue', 2],
['CUVE', 'Grand récipient du vigneron|Le vin y fermente', 2],
['DIVA', 'Cantatrice célèbre|Elle fait des caprices', 2],
['DOME', 'Coupole d’église|Toit arrondi', 2],
['DUEL', 'Combat à deux|Affaire d’honneur', 2],
['EPIS', 'Ils dorent dans le champ|Mèches rebelles', 2],
['ETAL', 'Table du marchand|Le boucher y pose la viande', 3],
['EXIL', 'Loin de son pays|Départ forcé', 2],
['FARD', 'Maquillage du visage|Sans… , franchement', 2],
['FIEL', 'Amertume méchante|Bile, au figuré', 3],
['FLAN', 'Dessert aux œufs|En rester comme deux ronds de…', 2],
['FOIE', 'Organe du filtre|Il souffre après la fête', 1],
['FOND', 'Le bas de la casserole|Course de longue haleine', 1],
['FRAC', 'Habit de cérémonie|Queue-de-pie', 3],
['GRAS', 'Riche en matière huileuse|Mardi… , jour de carnaval', 1],
['GRUE', 'Elle lève les charges|Grand oiseau migrateur', 2],
['HAIE', 'Clôture de verdure|Obstacle du coureur', 1],
['HOUX', 'Feuilles piquantes de Noël|Ses baies sont rouges', 2],
['HUES', 'Cris d’hostilité|Le public les lance', 3],
['IMAM', 'Il dirige la prière|Guide de la mosquée', 2],
['JARS', 'Mâle de l’oie|Il siffle en gardant la ferme', 3],
['JOUG', 'Pièce de bois des bœufs|Domination pesante', 3],
['LACS', 'Étendues d’eau douce|Annecy et Léman en sont', 2],
['LAIE', 'Femelle du sanglier|Elle mène ses marcassins', 3],
['LEST', 'Poids du navire|Jeter du… , alléger', 2],
['LIEN', 'Ce qui attache|Il unit deux personnes', 1],
['LIRE', 'Parcourir des yeux|Ancienne monnaie italienne', 1],
['LOTO', 'Jeu de nombres tirés|On y coche sa grille', 1],
['LUXE', 'Grand confort coûteux|Le contraire du dénuement', 1],
['MAGE', 'Ils étaient trois à Bethléem|Savant de l’Orient', 2],
['MAIL', 'Allée bordée d’arbres|Courrier électronique', 2],
['MAUX', 'Douleurs multiples|Les cent… du malade', 2],
['MELE', 'Brassé ensemble|Il s’en… , il intervient', 2],
['MOTO', 'Deux-roues rapide|Elle a un guidon et un moteur', 1],
['MUSC', 'Parfum animal|Base de l’eau de toilette', 3],
['NAIN', 'Tout petit|Ils étaient sept avec Blanche-Neige', 1],
['NEON', 'Tube lumineux|Gaz de l’enseigne', 2],
['NOEL', 'Fête du 25 décembre|On y décore un sapin', 1],
['NORD', 'Direction de la boussole|Perdre le… , s’égarer', 1],
['OBUS', 'Projectile du canon|Il siffle avant d’exploser', 2],
['ONYX', 'Pierre fine noire|Variété d’agate', 3],
['ORAL', 'Épreuve à la voix|Le contraire d’écrit', 1],
['ORIN', 'Cordage de la bouée|Il retient l’ancre', 3],
['PAGE', 'Feuille du livre|Jeune serviteur du seigneur', 1],
['PALE', 'Sans couleurs|Elle brasse l’air de l’hélice', 1],
['PARI', 'Mise sur un résultat|Il se tient ou se perd', 1],
['PATE', 'Mélange du boulanger|Elle cuit à l’eau salée', 1],
['PEUR', 'Elle serre le ventre|Sentiment du danger', 1],
['PIEU', 'Poteau planté en terre|Lit, familièrement', 2],
['PILE', 'Elle donne du courant|Tas bien rangé', 1],
['PLAN', 'Dessin de la maison|Projet organisé', 1],
['PLIE', 'Poisson plat|Courbé en deux', 2],
['POLE', 'Extrémité du globe|Il attire l’aiguille', 2],
['PUCE', 'Insecte qui saute|Elle fait fonctionner l’ordinateur', 1],
['QUAI', 'Bord du port|On y attend le train', 1],
['RAIL', 'Le train y roule|Barre d’acier du chemin de fer', 1],
['RAME', 'Elle fait avancer la barque|Convoi du métro', 1],
['RATE', 'Organe près de l’estomac|Se dilater la… , rire fort', 2],
['REIN', 'Il filtre le sang|Avoir les… solides', 2],
['RIME', 'Fin de vers qui sonne pareil|Sans… ni raison', 2],
['ROND', 'Forme du cercle|Il n’a pas d’angles', 1],
['SAGE', 'Plein de raison|Enfant tranquille', 1],
['SAUT', 'Bond en l’air|Il se fait en longueur ou en hauteur', 1],
['SOIE', 'Tissu du ver|Étoffe douce et brillante', 1],
['SOUS', 'Petite monnaie d’autrefois|Petite monnaie d’autrefois', 1],
['STOP', 'Panneau rouge à huit côtés|On lève le pouce pour lui', 1],
['SUIE', 'Noir de la cheminée|Le ramoneur la retire', 2],
['TAIE', 'Housse de l’oreiller|Voile sur la cornée', 2],
['TARD', 'Après l’heure|Mieux vaut… que jamais', 1],
['TAXI', 'Voiture avec chauffeur|Il a un compteur', 1],
['TIGE', 'Elle porte la fleur|Partie longue et fine', 1],
['TOME', 'Volume d’une série|Le premier d’une saga', 2],
['TORT', 'Il n’a pas raison|Dommage causé', 1],
['TRAM', 'Il roule sur rails en ville|Transport à voie ferrée', 2],
['TUBE', 'Cylindre creux|Chanson à succès', 1],
['URNE', 'On y glisse son bulletin|Vase des cendres', 2],
['VOEU', 'Souhait formulé|On en fait au Nouvel An', 2],
['VOLT', 'Unité de tension|Il mesure l’électricité', 2],
['YOGA', 'Discipline des postures|On y travaille le souffle', 1],
['ZEBU', 'Bœuf à bosse|Bovin de l’Inde', 3],
];

const Y5 = [
['ABIME', 'Gouffre sans fond|Profondeur vertigineuse', 2],
['ADIEU', 'Salut du départ définitif|On le dit en partant pour toujours', 1],
['AIGLE', 'Rapace au regard perçant|Roi des airs', 1],
['ALGUE', 'Plante de la mer|Elle échoue sur la plage', 2],
['AMBRE', 'Résine fossile|Il piège parfois un insecte', 3],
['ANGLE', 'Coin de la pièce|Le droit fait quatre-vingt-dix degrés', 1],
['ARBRE', 'Il perd ses feuilles en automne|Il donne de l’ombre', 1],
['ARENE', 'Le taureau y entre|Cercle de sable du combat', 2],
['AVOIR', 'Posséder|Le contraire du doit, en comptabilité', 1],
['BAGUE', 'Anneau du doigt|Cadeau des fiançailles', 1],
['BALAI', 'Il chasse la poussière|Monture de la sorcière', 1],
['BARBE', 'Poils du menton|Elle pousse sans qu’on la sème', 1],
['BILAN', 'Compte de fin d’année|On le tire après coup', 2],
['BLOND', 'Cheveux clairs|Bière dorée', 1],
['BOUEE', 'Elle flotte pour sauver|Repère du chenal', 2],
['BRUIT', 'Son désagréable|Rumeur qui court', 1],
['CABLE', 'Gros fil d’acier|Il transporte le courant', 1],
['CANOT', 'Petite embarcation|On y rame assis', 2],
['CHAMP', 'Le blé y pousse|Terrain cultivé', 1],
['CHIEN', 'Meilleur ami de l’homme|Il remue la queue', 1],
['CHOIX', 'Il faut trancher|Sélection faite', 1],
['CIBLE', 'On vise en son centre|But de la flèche', 1],
['CIDRE', 'Boisson de pomme|Spécialité normande', 2],
['CIMES', 'Sommets des arbres|Points les plus hauts', 2],
['CLOUS', 'Le marteau les enfonce|Passage protégé du piéton', 2],
['COUDE', 'Articulation du bras|Virage brusque de la route', 1],
['CRABE', 'Il marche de côté|Pinces sur le sable', 1],
['CRAIE', 'Elle écrit au tableau|Roche blanche et tendre', 2],
['CREME', 'Elle nappe le dessert|Le meilleur du meilleur', 1],
['CROIX', 'Deux traits qui se coupent|On la fait sur le bulletin', 1],
['DIGUE', 'Elle retient la mer|Barrage de pierres', 2],
['DROIT', 'Sans courbure|Étude des lois', 1],
['ECOLE', 'Les enfants y apprennent|Bâtiment de la classe', 1],
['ECUME', 'Mousse de la vague|Elle blanchit la crête', 2],
['ENCRE', 'Le stylo en contient|La seiche en projette', 1],
['ETAGE', 'On y monte par l’escalier|Niveau de l’immeuble', 1],
['ETUDE', 'Travail de recherche|Bureau du notaire', 1],
['FERME', 'Elle abrite les vaches|Solide, sans mollesse', 1],
['FLEUR', 'Elle sent bon au printemps|On l’offre en bouquet', 1],
['FOULE', 'Beaucoup de monde|Elle se presse au concert', 1],
['FRUIT', 'La pomme en est un|Résultat d’un effort', 1],
['GARDE', 'Il surveille l’entrée|Prendre… , faire attention', 1],
['GLACE', 'Eau devenue dure|Dessert du glacier|Miroir ancien', 1],
['GRAIN', 'Semence du champ|Averse soudaine en mer', 2],
['HERBE', 'Le mouton la broute|Verte sous les pieds', 1],
['HIVER', 'Saison du froid|Il commence en décembre', 1],
['HUILE', 'Elle graisse le moteur|On en met dans la salade', 1],
['IMAGE', 'Elle illustre le texte|Sage comme une…', 1],
['JAUNE', 'Couleur du citron|Centre de l’œuf', 1],
['LAMPE', 'Elle éclaire la pièce|Celle d’Aladin cache un génie', 1],
['LARME', 'Goutte du chagrin|Elle roule sur la joue', 1],
['LIVRE', 'Il a des pages et une couverture|Ancienne monnaie', 1],
['LOUPE', 'Elle grossit les détails|Verre du bijoutier', 2],
['MERLE', 'Oiseau noir au bec jaune|Il siffle au jardin', 2],
['MONDE', 'La Terre entière|Beaucoup de gens', 1],
['NEIGE', 'Elle tombe en flocons|Elle blanchit le paysage', 1],
['NUAGE', 'Il cache le soleil|Il flotte dans le ciel', 1],
['OMBRE', 'Elle suit celui qui marche|Zone à l’abri du soleil', 1],
['ORAGE', 'Éclairs et tonnerre|Il éclate en été', 1],
['PATTE', 'Membre de l’animal|Le chat en a quatre', 1],
['PERLE', 'Bijou de l’huître|Erreur cocasse', 2],
['PIANO', 'Instrument à touches|On l’accorde régulièrement', 1],
['PISTE', 'Trace à suivre|Elle descend la montagne', 1],
['PLAGE', 'Sable au bord de l’eau|On y étend sa serviette', 1],
['PLUIE', 'Gouttes tombées du ciel|Gouttes du ciel', 1],
['POIRE', 'Fruit du verger|Se fendre la…, rire', 1],
['POMME', 'Fruit du verger|Celle de Newton est célèbre', 1],
['PORTE', 'Elle s’ouvre et se ferme|On y frappe avant d’entrer', 1],
['POUCE', 'Doigt le plus court|On le lève pour approuver', 1],
['POULE', 'Elle pond les œufs|Groupe d’un tournoi', 1],
['RADIS', 'Petit légume rose|On le croque avec du sel', 2],
['REGLE', 'Elle trace des traits droits|Loi à respecter', 1],
['ROUTE', 'Le goudron la recouvre|On la prend pour partir', 1],
['RUCHE', 'Maison des abeilles|Elle bourdonne au printemps', 2],
['SABLE', 'Il glisse dans le sablier|Grains de la plage', 1],
['SALLE', 'Pièce de la maison|On y projette les films', 1],
['SEUIL', 'Pas de la porte|Limite à ne pas franchir', 2],
['SIGNE', 'Geste qui indique|Il annonce quelque chose', 1],
['SOLDE', 'Reste à payer|Prix cassé de janvier', 2],
['SUCRE', 'Il adoucit le café|Betterave ou canne', 1],
['TABLE', 'On y prend ses repas|Elle a souvent quatre pieds', 1],
['TERRE', 'Notre planète|On la retourne au jardin', 1],
['TIGRE', 'Grand félin rayé|Fauve d’Asie', 1],
['TOILE', 'Support du peintre|L’araignée la tisse', 1],
['VAGUE', 'Elle déferle sur la plage|Imprécis, flou', 1],
['VEINE', 'Elle ramène le sang|Chance, familièrement', 2],
['VERRE', 'On y boit|Il casse en tombant', 1],
['VIGNE', 'Elle donne le raisin|Rangs du coteau', 2],
['VILLE', 'Plus grande que le village|Elle a des quartiers', 1],
['VOILE', 'Le vent la pousse|Tissu qui cache le visage', 1],
];

const Y6 = [
['AMANDE', 'Fruit sec du verger|Elle se cache dans sa coque', 2],
['ARGENT', 'Métal blanc précieux|On le dépense', 1],
['BALCON', 'Il avance sur la façade|On y met des fleurs', 1],
['BEURRE', 'Il fond dans la poêle|Produit de la baratte', 1],
['BOUCLE', 'Anneau de la ceinture|Mèche enroulée', 1],
['BUREAU', 'Table de travail|Lieu où l’on travaille assis', 1],
['CAHIER', 'Il a des pages lignées|On y écrit ses leçons', 1],
['CANARD', 'Il barbote sur la mare|Journal, familièrement', 1],
['CARTON', 'Boîte du déménagement|Il sanctionne le joueur', 1],
['CHAISE', 'On s’y assoit|Elle a un dossier', 1],
['CHEMIN', 'Petite route de campagne|Il mène quelque part', 1],
['CHEVAL', 'Il galope au pré|Monture du cavalier', 1],
['CLOCHE', 'Elle appelle à la messe|On la fait tinter', 1],
['DEBOUT', 'Sur ses jambes|Le contraire d’assis', 1],
['DESSIN', 'Trait du crayon|Il illustre l’album', 1],
['ECLAIR', 'Il zèbre le ciel|Gâteau au chocolat', 1],
['ENFANT', 'Il grandit vite|Il n’est pas encore adulte', 1],
['ESCALE', 'Arrêt du voyage|Le bateau y fait halte', 2],
['ETOILE', 'Elle brille la nuit|Vedette célèbre', 1],
['GARAGE', 'Abri de la voiture|On y répare les moteurs', 1],
['GLACON', 'Cube du congélateur|Il rafraîchit le verre', 2],
['JARDIN', 'On y plante des légumes|Espace vert de la maison', 1],
['LAPINS', 'Ils creusent des terriers|Poser un… , ne pas venir', 2],
['LEGUME', 'La carotte en est un|On le trouve au potager', 1],
['MAISON', 'On y habite|Elle a un toit et des murs', 1],
['MARCHE', 'Elle se monte dans l’escalier|Lieu des étals du samedi', 1],
['MIETTE', 'Petit morceau de pain|Il n’en reste pas une', 2],
['MIROIR', 'Il renvoie l’image|On s’y regarde le matin', 1],
['MOUCHE', 'Elle tourne autour du plat|Prendre la… , se vexer', 1],
['MOUTON', 'Il donne la laine|On le compte pour s’endormir', 1],
['NUAGES', 'Ils voilent le soleil|Ils annoncent la pluie', 1],
['ORANGE', 'Agrume juteux|Couleur entre rouge et jaune', 1],
['PAILLE', 'On y boit son jus|Tige sèche du blé', 1],
['PANIER', 'On y met les courses|Cible du basketteur', 1],
['PEIGNE', 'Il démêle les cheveux|Passer au… fin, fouiller', 1],
['PIERRE', 'Caillou de la carrière|Elle roule et n’amasse pas mousse', 1],
['PLANTE', 'Elle pousse en pot|Dessous du pied', 1],
['POISON', 'Il tue à petite dose|Substance mortelle', 2],
['RAISIN', 'Fruit de la vigne|Il donne le vin', 1],
['RENARD', 'Il rôde autour du poulailler|Rusé de la fable', 1],
['SALADE', 'Feuilles à l’huile et au vinaigre|Raconter des… , mentir', 1],
['SAVANE', 'Grande plaine d’herbes|Elle abrite les lions', 2],
['SOLEIL', 'Il se lève à l’est|Étoile qui nous chauffe', 1],
['SOURIS', 'Elle grignote le fromage|On la déplace sur le tapis', 1],
['TIROIR', 'On l’ouvre en tirant|Il coulisse dans le meuble', 1],
['TOMATE', 'Rouge dans la salade|Fruit qu’on croit légume', 1],
['VIOLON', 'Il a quatre cordes|On en joue avec un archet', 1],
['VOISIN', 'Il habite à côté|On lui emprunte du sel', 1],
];

const Y7 = [
['ABEILLE', 'Elle butine de fleur en fleur|Ouvrière de la ruche', 1],
['ANIMAUX', 'Ils peuplent la ferme|Chat, chien et compagnie', 1],
['AUTOMNE', 'Saison des feuilles mortes|Entre l’été et l’hiver', 1],
['CHAPEAU', 'Il couvre la tête|On le tire pour saluer', 1],
['CHATEAU', 'Demeure du seigneur|Il a des tours et un donjon', 1],
['COUTEAU', 'Il coupe le pain|Lame à manche', 1],
['CUISINE', 'On y prépare les repas|Pièce des casseroles', 1],
['ECHELLE', 'On y monte barreau par barreau|Rapport du plan à la réalité', 1],
['ETOILES', 'Elles constellent la nuit|On les compte pour l’hôtel', 1],
['FENETRE', 'Elle laisse entrer le jour|On l’ouvre pour aérer', 1],
['FROMAGE', 'Il se fait avec du lait|Camembert ou comté', 1],
['GRENIER', 'Sous les toits|On y range ce qu’on ne jette pas', 1],
['JOURNAL', 'On le lit au petit-déjeuner|Il paraît chaque matin', 1],
['LUMIERE', 'Elle chasse l’obscurité|On l’allume en entrant', 1],
['MARTEAU', 'Il enfonce les clous|Outil à manche et à tête', 1],
['MUSIQUE', 'Elle s’écoute et se joue|Art des sons', 1],
['POMPIER', 'Il éteint les incendies|Il descend le long d’un mât', 1],
['RIVIERE', 'Elle se jette dans le fleuve|Cours d’eau du bocage', 1],
['SILENCE', 'Absence de bruit|On le demande au concert', 1],
['TEMPETE', 'Vent très violent|Elle secoue les bateaux', 1],
['THEATRE', 'On y joue des pièces|Scène et coulisses', 1],
['VELOURS', 'Tissu doux au toucher|Faire patte de…, être doux', 2],
['VILLAGE', 'Plus petit qu’une ville|Il a souvent une église', 1],
['VOITURE', 'Elle roule à quatre roues|On la gare au parking', 1],
];

const Y8 = [
['ABRICOTS', 'Fruits orangés de l’été|Ils viennent du Roussillon', 2],
['CHEMINEE', 'Le feu y crépite|Le Père Noël y descend', 1],
['DIMANCHE', 'Jour du repos|Il suit le samedi', 1],
['ESCALIER', 'On le monte marche à marche|Il mène à l’étage', 1],
['FONTAINE', 'Elle coule sur la place|On y puisait l’eau', 1],
['MONTAGNE', 'Elle culmine à plusieurs sommets|On y fait du ski', 1],
['ORCHIDEE', 'Fleur exotique en pot|Elle demande peu d’eau', 2],
['PEINTURE', 'Le pinceau l’étale|Art de la toile', 1],
['TROTTOIR', 'Le piéton y marche|Bordure de la rue', 1],
];

module.exports = { Y3, Y4, Y5, Y6, Y7, Y8 };
