// =====================================================================
//  MOTS FLÉCHÉS — dictionnaire.
//  Format : [MOT, définition, niveau] · niveau 1=facile 2=moyen 3=difficile
//  Les mots sont SANS accent, en majuscules (A-Z uniquement).
//  Pour enrichir le jeu : ajoute simplement des entrées dans les listes.
// =====================================================================

const W4 = [
    ['PONT', 'Ouvrage pour traverser une rivière', 1],
    ['CHAT', 'Félin qui ronronne', 1],
    ['ROSE', 'Fleur du jardin, souvent rouge', 1],
    ['LUNE', 'Astre de la nuit', 1],
    ['MAIN', 'Elle a cinq doigts', 1],
    ['PIED', 'Il porte la chaussure', 1],
    ['NUIT', 'Elle succède au jour', 1],
    ['JOUR', 'Entre deux nuits', 1],
    ['MIEL', 'Douceur des abeilles', 1],
    ['SOIR', 'Fin de journée', 1],
    ['VENT', 'Il fait tourner les moulins', 1],
    ['MERE', 'Elle a des enfants', 1],
    ['PERE', 'Papa, plus solennel', 1],
    ['VELO', 'Deux roues à pédales', 1],
    ['PAIN', 'On le coupe en tranches', 1],
    ['PLAT', 'Contenu du repas', 1],
    ['PORT', 'Abri pour les bateaux', 1],
    ['TOIT', "Il couvre la maison", 1],
    ['LAIT', 'Blanc, il vient de la vache', 1],
    ['CIEL', 'Au-dessus de nos têtes', 1],
    ['RIRE', "Éclat de joie", 1],
    ['CAFE', 'Noir et serré le matin', 1],
    ['DENT', 'Elle mord', 1],
    ['TETE', 'Elle porte le chapeau', 1],
    ['TOUR', 'Elle domine la ville', 1],
    ['SAUT', "Bond en l'air", 1],
    ['NAGE', "Déplacement dans l'eau", 1],
];

const W5 = [
    ['ARBRE', 'Il a un tronc et des branches', 1],
    ['AVION', 'Il vole avec des passagers', 1],
    ['AMOUR', 'Sentiment du cœur', 1],
    ['ANGLE', 'Coin, en géométrie', 2],
    ['BILLE', 'Petite boule de verre', 1],
    ['BOTTE', 'Chaussure de pluie', 1],
    ['BALLE', 'Elle rebondit', 1],
    ['BATON', 'Morceau de bois allongé', 1],
    ['CHIEN', "Meilleur ami de l'homme", 1],
    ['CRABE', 'Il marche de côté', 1],
    ['CARTE', 'Elle montre le chemin', 1],
    ['CIBLE', 'On vise en son centre', 2],
    ['DANSE', 'On la fait en musique', 1],
    ['DOIGT', 'Il y en a cinq par main', 1],
    ['DEBUT', 'Le contraire de la fin', 1],
    ['DRAME', 'Pièce très sérieuse', 2],
    ['ECOLE', "On y apprend à lire", 1],
    ['ETAGE', "Niveau d'un immeuble", 1],
    ['EPICE', 'Elle relève les plats', 2],
    ['ELEVE', "Il apprend à l'école", 1],
    ['FLEUR', 'Elle sent bon au jardin', 1],
    ['FUSEE', "Elle part vers l'espace", 1],
    ['FERME', 'Maison des vaches', 1],
    ['FORET', 'Beaucoup d’arbres', 1],
    ['GLACE', 'Dessert froid', 1],
    ['GRAIN', 'Petite graine', 2],
    ['GENOU', 'Articulation de la jambe', 1],
    ['GOMME', 'Elle efface le crayon', 1],
    ['HOTEL', 'On y dort en voyage', 1],
    ['HIVER', 'Saison la plus froide', 1],
    ['HERBE', 'Verte, dans le pré', 1],
    ['HACHE', 'Elle fend le bois', 2],
    ['IMAGE', 'Photo ou dessin', 1],
    ['IDEAL', 'Parfait, rêvé', 2],
    ['INDEX', 'Doigt qui montre', 2],
    ['IGLOO', 'Maison de glace', 2],
    ['JOUER', 'Ce que font les enfants', 1],
    ['JEUDI', 'Après mercredi', 1],
    ['JUPON', 'Sous la jupe', 3],
    ['JUSTE', 'Équitable', 2],
    ['LIVRE', 'Il se lit page après page', 1],
    ['LUNDI', 'Début de semaine', 1],
    ['LAMPE', 'Elle éclaire la pièce', 1],
    ['LARME', 'Elle coule quand on pleure', 1],
    ['MUSEE', 'On y voit des tableaux', 1],
    ['MELON', 'Fruit sucré de l’été', 1],
    ['MARIN', 'Homme des bateaux', 1],
    ['MONDE', 'La Terre entière', 1],
    ['NAGER', "Se déplacer dans l'eau", 1],
    ['NEIGE', 'Blanche, elle tombe en hiver', 1],
    ['NUAGE', 'Il cache parfois le soleil', 1],
    ['NAVET', 'Légume racine', 2],
    ['OCEAN', "Vaste étendue d'eau salée", 1],
    ['OLIVE', "Petit fruit de l'apéritif", 1],
    ['ORAGE', 'Éclairs et tonnerre', 1],
    ['OMBRE', 'Elle suit au soleil', 1],
    ['PIANO', 'Instrument à touches', 1],
    ['PLAGE', 'Sable au bord de la mer', 1],
    ['PORTE', 'On la pousse pour entrer', 1],
    ['POMME', 'Fruit rouge ou vert', 1],
    ['RADIO', "On l'écoute pour la musique", 1],
    ['ROUTE', 'Les voitures y roulent', 1],
    ['REVER', 'Ce qu’on fait en dormant', 1],
    ['RONDE', 'Forme du cercle', 1],
    ['SUCRE', 'Il adoucit le café', 1],
    ['SALLE', 'Grande pièce', 1],
    ['SIROP', 'Sucré, à diluer', 1],
    ['SABLE', 'Grains de la plage', 1],
    ['TABLE', 'Meuble à quatre pieds', 1],
    ['TIGRE', 'Grand félin rayé', 1],
    ['TRAIN', 'Il roule sur des rails', 1],
    ['TERRE', 'Notre planète', 1],
    ['USINE', 'Bâtiment où on fabrique', 1],
    ['UNION', 'Fait la force', 2],
    ['UTILE', 'Qui sert à quelque chose', 1],
    ['USAGE', 'Manière de se servir', 2],
    ['VILLE', 'Plus grande qu’un village', 1],
    ['VERRE', "On y boit de l'eau", 1],
    ['VOILE', 'Elle pousse le bateau', 1],
    ['VIVRE', 'Être en vie', 1],
];

const W6 = [
    ['ANIMAL', 'Le chien en est un', 1],
    ['ARGENT', 'Métal précieux ou monnaie', 1],
    ['AUTEUR', "Il écrit des livres", 2],
    ['AVOCAT', 'Fruit vert ou homme de loi', 2],
    ['BALLON', 'On y joue au foot', 1],
    ['BUREAU', 'Meuble pour travailler', 1],
    ['BONBON', 'Sucrerie des enfants', 1],
    ['BATEAU', 'Il navigue sur l’eau', 1],
    ['CHEVAL', 'On le monte en selle', 1],
    ['CARTON', 'Boîte de déménagement', 1],
    ['CANARD', 'Oiseau de la mare', 1],
    ['CERISE', 'Petit fruit rouge à noyau', 1],
    ['DESSIN', 'Fait au crayon', 1],
    ['DOUCHE', 'On s’y lave debout', 1],
    ['DANGER', 'Il faut s’en méfier', 1],
    ['DOMINO', 'Petit rectangle à points', 2],
    ['ENFANT', 'Il n’est pas encore adulte', 1],
    ['ETOILE', 'Elle brille dans la nuit', 1],
    ['EPAULE', 'Entre le cou et le bras', 1],
    ['ESCALE', 'Arrêt du voyage', 2],
    ['FLACON', 'Petite bouteille', 2],
    ['FUSION', 'Passage à l’état liquide', 3],
    ['FACILE', 'Le contraire de difficile', 1],
    ['FERMER', 'Le contraire d’ouvrir', 1],
    ['GARAGE', 'Abri de la voiture', 1],
    ['GATEAU', 'Dessert d’anniversaire', 1],
    ['GLACON', 'Cube froid dans le verre', 1],
    ['GRAINE', 'On la sème', 1],
    ['HAMEAU', 'Tout petit village', 3],
    ['HUMEUR', 'Bonne ou mauvaise', 2],
    ['HANCHE', 'Haut de la jambe', 2],
    ['HOMARD', 'Crustacé à grosses pinces', 2],
    ['INDICE', 'Il met sur la piste', 2],
    ['ISOLER', 'Mettre à part', 2],
    ['IMPACT', 'Choc, effet', 2],
    ['IMAGES', 'Plusieurs photos', 1],
    ['JARDIN', 'On y cultive des fleurs', 1],
    ['JAUNIR', 'Devenir jaune', 2],
    ['JUMEAU', 'Né le même jour', 2],
    ['JOUEUR', "Il participe à la partie", 1],
    ['LEGUME', 'La carotte en est un', 1],
    ['LOUTRE', 'Elle nage dans la rivière', 2],
    ['LANCER', 'Jeter au loin', 1],
    ['LEZARD', 'Petit reptile au soleil', 2],
    ['MAISON', 'On y habite', 1],
    ['MOUTON', 'Il donne la laine', 1],
    ['MIROIR', 'On s’y regarde', 1],
    ['MARCHE', 'On y achète des légumes', 1],
    ['NAVIRE', 'Grand bateau', 1],
    ['NATURE', 'Forêts, champs et rivières', 1],
    ['NOUGAT', 'Confiserie aux amandes', 3],
    ['NOMBRE', 'Le sept en est un', 1],
    ['ORANGE', 'Fruit et couleur', 1],
    ['OISEAU', 'Il a des plumes', 1],
    ['OLIVES', "Fruits de l'apéritif", 1],
    ['OUTILS', 'Marteau, pince et tournevis', 1],
    ['PANIER', "On y met les courses", 1],
    ['POISON', 'Substance mortelle', 2],
    ['PLANTE', 'Elle pousse dans un pot', 1],
    ['PRINCE', 'Fils du roi', 1],
    ['RENARD', 'Rusé, à la queue rousse', 1],
    ['RACINE', "Partie de l'arbre sous terre", 1],
    ['RIVAGE', 'Bord de la mer', 2],
    ['ROSIER', 'Arbuste à roses', 2],
    ['SOLEIL', 'Il éclaire le jour', 1],
    ['SOURIS', "Petit rongeur ou objet d'ordinateur", 1],
    ['SIRENE', 'Femme-poisson des légendes', 2],
    ['SAVANE', 'Plaine des lions', 2],
    ['TOMATE', 'Rouge, dans la salade', 1],
    ['TUNNEL', 'Passage sous la terre', 1],
    ['TRESOR', 'Coffre des pirates', 1],
    ['TIROIR', 'Il se tire du meuble', 1],
    ['UNIQUE', "Il n'y en a qu'un", 2],
    ['URGENT', 'Qui ne peut pas attendre', 2],
    ['USINES', 'Lieux de fabrication', 1],
    ['UNITES', 'Éléments comptés un à un', 3],
    ['VOYAGE', 'Départ vers ailleurs', 1],
    ['VIOLON', 'Instrument à archet', 1],
    ['VERGER', "Champ d'arbres fruitiers", 2],
    ['VOISIN', 'Il habite à côté', 1],
];

const W7 = [
    ['ARTISTE', 'Peintre ou musicien', 2],
    ['ANCETRE', 'Aïeul lointain', 3],
    ['ANIMAUX', 'Le zoo en est plein', 2],
    ['AMANDES', 'Fruits secs du nougat', 3],
    ['BANQUET', 'Grand repas de fête', 3],
    ['BISCUIT', 'Petit gâteau sec', 2],
    ['BRIGADE', "Équipe d'intervention", 3],
    ['BALCONS', 'Terrasses en hauteur', 2],
    ['CHATEAU', 'Demeure du roi', 2],
    ['CUISINE', 'Pièce des casseroles', 2],
    ['CAMPING', 'Vacances sous la tente', 2],
    ['CHANSON', 'On la chante', 2],
    ['DIAMANT', 'Pierre très précieuse', 2],
    ['DESSERT', 'Fin du repas', 2],
    ['DOCTEUR', 'Il soigne les malades', 2],
    ['DRAGONS', 'Ils crachent le feu', 2],
    ['ETAGERE', 'Planche pour les livres', 3],
    ['EPINARD', 'Légume vert de Popeye', 3],
    ['EMOTION', 'Ce que le cœur ressent', 3],
    ['ECLAIRS', 'Ils zèbrent le ciel', 2],
    ['FROMAGE', 'Il se fait avec du lait', 2],
    ['FENETRE', 'Elle laisse entrer le jour', 2],
    ['FALAISE', 'Haute paroi au bord de mer', 3],
    ['FORTUNE', 'Grande richesse', 3],
    ['GALETTE', 'On y cache une fève', 3],
    ['GRENIER', 'Sous le toit', 3],
    ['GARDIEN', 'Il surveille', 2],
    ['GLACIER', 'Fleuve de glace', 3],
    ['HORLOGE', 'Elle donne l’heure', 2],
    ['HARICOT', 'Vert, il se mange', 2],
    ['HOMARDS', 'Crustacés à pinces', 3],
    ['HAUTEUR', 'Distance vers le haut', 3],
    ['INSECTE', 'La fourmi en est un', 2],
    ['IMMENSE', 'Très très grand', 3],
    ['ISOLOIR', 'Cabine pour voter', 3],
    ['INVITES', 'Ils viennent à la fête', 2],
    ['JOURNAL', 'On y lit les nouvelles', 2],
    ['JUMELLE', 'Sœur née le même jour', 3],
    ['JARDINS', 'Espaces verts cultivés', 2],
    ['JOYEUSE', 'Pleine de gaieté', 3],
    ['LUMIERE', 'Elle chasse le noir', 2],
    ['LOTERIE', 'Jeu de tirage au sort', 3],
    ['LIBERTE', 'Devise avec égalité', 2],
    ['LEZARDS', 'Reptiles des vieux murs', 3],
    ['MACHINE', 'Elle fonctionne toute seule', 2],
    ['MUSIQUE', 'Art des sons', 2],
    ['MARTEAU', 'Il enfonce les clous', 2],
    ['MONTAGE', 'Assemblage des images', 3],
    ['NOUVEAU', 'Qui vient d’arriver', 2],
    ['NUMEROS', 'Chiffres des maisons', 2],
    ['NAVIRES', 'Bateaux de haute mer', 2],
    ['NECTARS', 'Boissons des dieux', 3],
    ['OUVRAGE', 'Travail ou livre', 3],
    ['OCTOBRE', 'Mois des feuilles mortes', 2],
    ['ORANGER', 'Arbre à agrumes', 3],
    ['OREILLE', 'Elle entend', 2],
    ['PEINTRE', 'Il tient un pinceau', 2],
    ['PIRATES', 'Bandits des mers', 2],
    ['POTAGER', 'Jardin de légumes', 3],
    ['PRAIRIE', 'Grand pré', 3],
    ['RECOLTE', 'Ramassage des cultures', 3],
    ['RIVIERE', 'Elle coule vers le fleuve', 2],
    ['ROULEAU', 'Il sert à peindre', 3],
    ['RENARDS', 'Rusés du bois', 2],
    ['SEMAINE', 'Elle a sept jours', 2],
    ['SOURIRE', 'Signe de bonne humeur', 2],
    ['SILENCE', 'Absence de bruit', 2],
    ['SARDINE', 'Petit poisson en boîte', 3],
    ['THEATRE', 'On y joue des pièces', 2],
    ['TOITURE', 'Ensemble du toit', 3],
    ['TRAJETS', 'Chemins parcourus', 3],
    ['TORTUES', 'Elles portent leur maison', 2],
    ['UNIVERS', 'Tout le cosmos', 2],
    ['URGENCE', 'Cas à traiter vite', 3],
    ['USAGERS', 'Ceux qui utilisent le service', 3],
    ['USINAGE', 'Façonnage des pièces', 3],
    ['VILLAGE', 'Plus petit qu’une ville', 2],
    ['VOITURE', 'Elle a quatre roues', 2],
    ['VERGERS', 'Champs de pommiers', 3],
    ['VOYAGES', 'Déplacements lointains', 2],
];

// Index : { longueur: { LETTRE: [ {m, d, n}, ... ] } }
function buildIndex(lists) {
    const idx = {};
    for (const [len, list] of Object.entries(lists)) {
        idx[len] = {};
        for (const [m, d, n] of list) {
            (idx[len][m[0]] = idx[len][m[0]] || []).push({ m, d, n });
        }
    }
    return idx;
}

const LISTS = { 4: W4, 5: W5, 6: W6, 7: W7 };

module.exports = {
    LISTS,
    INDEX: buildIndex(LISTS),
    all: () => Object.values(LISTS).flat(),
};