// =====================================================================
//  MOTS FLÉCHÉS — dictionnaire.
//  Format : ['MOT', 'définition 1|définition 2|…', niveau]
//    · plusieurs définitions séparées par « | » (tirage aléatoire chaque jour)
//    · niveau 1 = courant · 2 = moins courant · 3 = rare / expert
//  Mots SANS accent, en MAJUSCULES (A-Z uniquement).
// =====================================================================

const W3 = [
['AIL','Il parfume le gigot|Bulbe odorant',1],['AIR','On le respire|Mélodie|Allure',1],
['AMI','Copain fidèle|Il est cher au cœur',1],['ANE','Il a de longues oreilles|Baudet|Sot',1],
['ARC','Il lance des flèches|Courbe',1],['ART','La peinture en est un|Habileté',1],
['BAL','Soirée dansante|On y valse',1],['BEC','Bouche de l’oiseau|Pointe du broc',1],
['BOL','Récipient du petit-déjeuner|Chance, familièrement',1],['BUS','Transport en commun|Il a des arrêts',1],
['CAP','Pointe de terre|Direction du navire',2],['CAR','Bus de voyage|Parce que',2],
['CLE','Elle ouvre la porte|Solution|Signe musical',1],['COL','Passage en montagne|Haut de la chemise',2],
['CRI','Éclat de voix|Hurlement',1],['DES','On les lance au jeu|Cubes à points',1],
['DON','Cadeau généreux|Talent inné',2],['DOS','Derrière du corps|Il porte le sac',1],
['DUO','À deux|Couple de chanteurs',2],['EAU','On la boit|H2O|Elle coule',1],
['ETE','Saison chaude|Vacances scolaires',1],['FER','Métal du forgeron|Il repasse',1],
['FEU','Il brûle|Rouge au carrefour|Flamme',1],['FIL','Il sert à coudre|Conducteur électrique',1],
['FIN','Le mot du dernier chapitre|Délicat|Terme',1],['GAZ','Il alimente la cuisinière|État de la matière',2],
['GEL','Froid qui glace|Produit pour cheveux',2],['ILE','Terre entourée d’eau|Corse, par exemple',1],
['JEU','On y joue|Distraction|Ensemble de cartes',1],['JUS','Boisson de fruits|Sauce du rôti',1],
['LAC','Étendue d’eau douce|Léman, par exemple',1],['LIT','On y dort|Cours de la rivière',1],
['LOI','Règle du pays|Texte voté',1],['MAI','Mois du muguet|Après avril',1],
['MAL','Le contraire du bien|Douleur',1],['MER','Elle est salée|Étendue marine',1],
['MIE','Intérieur du pain|Contraire de croûte',2],['MUR','Il sépare les pièces|Cloison',1],
['NEZ','Il sent les odeurs|Odorat|Proue de l’avion',1],['NID','Maison des oiseaux|Abri douillet',1],
['NOM','Il désigne la personne|Patronyme',1],['NUL','Match sans vainqueur|Sans valeur',2],
['OIE','Oiseau de la ferme|Elle cacarde',2],['ORS','Métaux précieux, au pluriel|Dorures',3],
['OUI','Le contraire de non|Accord',1],['PAS','Enjambée|Négation|Passage étroit',1],
['PIC','Sommet pointu|Oiseau grimpeur|Maximum',2],['PIE','Oiseau noir et blanc voleur|Bavarde',2],
['PIN','Arbre à aiguilles|Résineux des Landes',1],['POT','Récipient de fleurs|Chance, familièrement',1],
['PRE','Champ d’herbe|Pâturage',2],['PUR','Sans mélange|Immaculé',2],
['RAT','Rongeur des caves|Il quitte le navire',1],['RIZ','Grain blanc du repas|Il pousse en rizière',1],
['ROI','Il porte la couronne|Chef du royaume|Carte à jouer',1],['RUE','Voie de la ville|Artère',1],
['SAC','On y met ses affaires|Bagage|Pillage',1],['SEC','Sans humidité|Aride|Maigre',1],
['SEL','Il relève les plats|Chlorure de sodium',1],['SOL','On marche dessus|Note de musique|Terrain',1],
['TAS','Grand amas|Monceau',1],['THE','Boisson chaude en feuilles|Infusion',1],
['TIR','Coup au but|Discipline sportive',2],['TON','Hauteur de la voix|Nuance de couleur',2],
['TOP','Signal de départ|Le meilleur',2],['VER','Il rampe dans la terre|Larve',1],
['VIN','Boisson de la vigne|Rouge ou blanc',1],['VIS','Elle se serre au tournevis|Spirale',2],
['VOL','Trajet en avion|Larcin',1],['VUE','Sens des yeux|Panorama',1],
['ZOO','Parc à animaux|On y voit des lions',1],['AGE','Nombre d’années|Époque',1],
['ANS','Ils comptent les années|Bougies du gâteau',1],['BAC','Examen de fin de lycée|Récipient|Bateau plat',2],
['BUT','Objectif|Il fait gagner au foot',1],['CRU','Terroir du vin|Non cuit',2],
['ECU','Ancienne monnaie|Bouclier',3],['EPI','Il porte les grains|Mèche rebelle',2],
['LAS','Fatigué|Épuisé',3],['NET','Propre|Clair|Sans bavure',2],
['OSE','Il tente sa chance|Il prend des risques',2],['PUB','Réclame|Bar anglais',2],
['RUZ','x',3],
].filter(w => w[1] !== 'x');

const W4 = [
['AILE','Elle porte l’oiseau|Partie de l’avion|Côté du bâtiment',1],['AIRE','Surface|Zone de repos|Nid de l’aigle',2],
['AMIE','Confidente|Camarade',1],['ANGE','Il a des ailes au ciel|Être très gentil',1],
['ARBRE','x',1],['BAIE','Golfe|Petit fruit rond',2],['BANC','Siège du parc|Amas de sable',1],
['BEAU','Joli|Agréable à voir',1],['BLEU','Couleur du ciel|Novice|Fromage',1],
['BOIS','Petite forêt|Matière du chêne|Cornes du cerf',1],['BOUE','Terre détrempée|Gadoue',1],
['BRAS','Il porte la main|Affluent du fleuve',1],['CAFE','Noir et serré le matin|Bistrot',1],
['CAVE','Sous-sol de la maison|On y garde le vin',1],['CHAT','Félin qui ronronne|Il fait ses griffes',1],
['CHER','Coûteux|Aimé',1],['CIEL','Au-dessus de nos têtes|Firmament',1],
['CLAN','Groupe soudé|Tribu',2],['COIN','Angle de la pièce|Endroit retiré',1],
['COUP','Choc|Fois',1],['COUR','Espace devant l’école|Entourage du roi',1],
['CRIS','Hurlements|Clameurs',1],['DAME','Femme|Pièce du jeu d’échecs',1],
['DENT','Elle mord|Elle pousse au bébé',1],['DOIS','Je suis obligé, en conjuguant',3],
['DOUX','Agréable au toucher|Sucré|Gentil',1],['DUOS','Chants à deux voix',3],
['EAUX','Elles coulent, au pluriel|Ondes',2],['ECHO','Son qui revient|Rumeur',2],
['ECRU','Blanc cassé|Non teint',3],['ELAN','Grand cerf du Nord|Mouvement vif',2],
['ETAT','Nation|Condition|Situation',1],['ETRE','Exister|Créature vivante',1],
['FEUX','Signaux de la route|Flammes',1],['FILM','On le regarde au cinéma|Pellicule',1],
['FOIN','Herbe séchée du grenier|Fourrage',2],['FOIS','Une, deux, trois...|Occurrence',1],
['FORT','Puissant|Château fortifié|Très',1],['FOUR','Il cuit le gâteau|Échec au théâtre',1],
['GARE','Les trains y arrivent|Attention !',1],['GENS','Les personnes|La foule',1],
['GOUT','Sens de la langue|Saveur|Penchant',1],['GRIS','Entre noir et blanc|Couleur du ciel de pluie',1],
['HAIE','Buisson taillé|Obstacle du coureur',2],['HIER','Le jour d’avant|Le passé',1],
['HUIT','Après sept|Chiffre',1],['IDEE','Pensée qui vient|Projet',1],
['ILES','Terres entourées d’eau',1],['JEUX','Divertissements|Olympiques',1],
['JOIE','Grand bonheur|Allégresse',1],['JOUE','Côté du visage|Il participe au jeu',1],
['JOUR','Entre deux nuits|Journée|Lumière',1],['LAIT','Blanc, il vient de la vache|Boisson du chat',1],
['LAME','Partie qui coupe|Vague',2],['LENT','Il prend son temps|Peu rapide',1],
['LION','Roi des animaux|Félin à crinière',1],['LIRE','Parcourir un livre|Déchiffrer',1],
['LOUP','Il hurle à la lune|Cousin sauvage du chien',1],['LUNE','Astre de la nuit|Satellite de la Terre',1],
['MAIN','Elle a cinq doigts|Elle serre',1],['MAIS','Céréale à épis|Cependant',1],
['MARS','Mois du printemps|Planète rouge',1],['MERE','Elle a des enfants|Maman',1],
['MIEL','Douceur des abeilles|Il sucre la tisane',1],['MOIS','Trente jours environ|Janvier en est un',1],
['MORT','Fin de la vie|Décès',1],['MOTS','Ils forment la phrase|Vocabulaire',1],
['MURS','Ils entourent la maison|Cloisons',1],['NAGE','Déplacement dans l’eau|Crawl ou brasse',1],
['NEUF','Après huit|Tout nouveau',1],['NOIR','Couleur de la nuit|Sombre',1],
['NUIT','Elle succède au jour|Obscurité',1],['ONDE','Vague|Signal radio',2],
['OURS','Il aime le miel|Plantigrade|Peu sociable',1],['PAIN','On le coupe en tranches|Baguette',1],
['PAIX','Contraire de la guerre|Calme',1],['PARC','Jardin public|Enclos',1],
['PEAU','Elle couvre le corps|Enveloppe du fruit',1],['PERE','Papa, plus solennel|Géniteur',1],
['PIED','Il porte la chaussure|Base|Mesure anglaise',1],['PLAT','Contenu du repas|Sans relief',1],
['PLUS','Davantage|Signe d’addition',1],['POIL','Il pousse sur la peau|Duvet',1],
['PONT','Ouvrage pour traverser|Étage du navire|Jour férié rallongé',1],['PORT','Abri pour les bateaux|Attitude',1],
['POUR','En faveur de|Afin de',1],['PRIX','Ce qu’on paie|Récompense',1],
['PUITS','x',1],['QUAI','Bord du port|On y attend le train',2],
['RIRE','Éclat de joie|S’esclaffer',1],['ROBE','Vêtement féminin|Couleur du cheval|Du vin',1],
['ROIS','Ils règnent|Fête des Rois',1],['ROSE','Fleur du jardin|Couleur tendre',1],
['ROUE','Elle tourne|Elle porte la voiture',1],['RUES','Voies de la ville',1],
['SAUT','Bond en l’air|Cabriole',1],['SEUL','Sans personne|Unique',1],
['SOIE','Tissu du ver|Étoffe brillante',2],['SOIF','Elle donne envie de boire|Besoin d’eau',1],
['SOIR','Fin de journée|Après le coucher du soleil',1],['SORT','Destin|Formule magique|Il quitte',1],
['SOUS','Dessous|Pièces de monnaie',1],['TAPI','Caché et immobile|Blotti',3],
['TASSE','x',1],['TETE','Elle porte le chapeau|Crâne|Sommet',1],
['TOIT','Il couvre la maison|Foyer',1],['TOUR','Elle domine la ville|Promenade|Rotation',1],
['TOUS','L’ensemble|Chacun',1],['VENT','Il fait tourner les moulins|Souffle',1],
['VERS','Ligne de poésie|En direction de|Larves',1],['VELO','Deux roues à pédales|Bicyclette',1],
['VIDE','Sans rien dedans|Néant',1],['VIES','Existences|Le chat en a neuf',1],
['VOIE','Chemin|Rails du train|Direction',1],['VRAI','Exact|Authentique',1],
['YEUX','Ils voient|Regard',1],['ZONE','Secteur|Périmètre',2],
['ACTE','Action|Partie de la pièce',2],['AUBE','Lever du jour|Vêtement du prêtre',2],
['CAPE','Manteau sans manches|Elle vole au vent',2],['CIRE','Elle vient de l’abeille|Elle fait briller',2],
['CUIR','Peau travaillée|Matière des bottes',2],['DIEU','Être suprême|Divinité',2],
['ECOT','Part à payer|Quote-part',3],['EMOI','Trouble du cœur|Agitation',3],
['FADE','Sans goût|Insipide',2],['GAIN','Ce qu’on gagne|Bénéfice',2],
['GEAI','Oiseau bavard des bois|Cousin de la pie',3],['HALE','Bronzage|Il tire la corde',3],
['HUTTE','x',2],['IRIS','Fleur violette|Partie colorée de l’œil',2],
['LOBE','Partie de l’oreille|Portion arrondie',3],['MATS','Ils portent les voiles|Sans brillant',3],
['NOTE','Elle se joue|Elle s’écrit|Facture',1],['ORGE','Céréale de la bière|Grain',2],
['PACTE','x',2],['PALE','Sans couleur|Partie de l’hélice',2],
['RAIE','Poisson plat|Trait|Séparation des cheveux',2],['RAME','Elle propulse la barque|Métro parisien',2],
['SAGE','Il est raisonnable|Philosophe',1],['SEVE','Sang de l’arbre|Vigueur',2],
['SITE','Lieu|Page internet',1],['TAUX','Pourcentage|Niveau',2],
['TROU','Ouverture|Cavité',1],['VASE','Il reçoit les fleurs|Boue du fond',2],
['VOIX','Elle chante|Suffrage',1],['ZELE','Ardeur au travail|Empressement',3],
].filter(w => w[1] !== 'x');

const W5 = [
['ABRIS','Refuges|Protections',2],['ACIER','Métal dur|Alliage du fer',2],['ADIEU','Dernier salut|Séparation',2],
['AIGLE','Rapace majestueux|Roi des airs',1],['AIMER','Éprouver de l’amour|Apprécier',1],
['ALLEE','Chemin du parc|Passage entre les rangs',2],['AMOUR','Sentiment du cœur|Passion',1],
['ANGLE','Coin|Point de vue|Il est droit ou aigu',2],['ANNEE','Douze mois|Elle commence en janvier',1],
['ARBRE','Il a un tronc et des branches|Chêne ou sapin',1],['ARENE','Cercle des taureaux|Sable du combat',3],
['ARGILE','x',2],['AVION','Il vole avec des passagers|Long-courrier',1],
['BAGUE','Bijou du doigt|Anneau',1],['BALLE','Elle rebondit|Projectile',1],
['BANCS','Sièges du parc|Amas de poissons',2],['BARBE','Poils du menton|Elle se rase',1],
['BATON','Morceau de bois allongé|Canne',1],['BEBES','Nourrissons|Tout-petits',1],
['BILLE','Petite boule de verre|Jeu de cour',1],['BLANC','Couleur de la neige|Vide|Œuf',1],
['BLOND','Cheveux clairs|Bière claire',1],['BOTTE','Chaussure de pluie|Assemblage de foin|Coup d’escrime',1],
['BOUCHE','x',1],['BOUTS','Extrémités|Morceaux',2],['BRIQUE','x',1],
['BRUIT','Son désagréable|Rumeur',1],['CABLE','Fil électrique|Gros cordage',2],
['CADRE','Il entoure le tableau|Encadrement|Employé',1],['CANNE','Aide à la marche|Plante à sucre',2],
['CARTE','Elle montre le chemin|Menu|Jeu',1],['CHAIR','Partie tendre|Peau',2],
['CHAMP','Terre cultivée|Domaine',1],['CHANT','Air chanté|Mélodie',1],
['CHIEN','Meilleur ami de l’homme|Il aboie',1],['CHOIX','Sélection|Option',1],
['CIBLE','On vise en son centre|Objectif',2],['CLOUS','Le marteau les enfonce|Passage piéton',2],
['COEUR','Il bat dans la poitrine|Centre|Couleur de cartes',1],['COINS','Angles|Recoins',2],
['COLLE','Elle fait tenir ensemble|Question difficile',1],['CORDE','Elle sert à attacher|Du violon',1],
['CORPS','L’ensemble du physique|Organisme',1],['COURS','Leçon|Écoulement de la rivière',1],
['CRABE','Il marche de côté|Crustacé à pinces',1],['CREME','Dessert onctueux|Dessus du lait',1],
['CROIX','Signe de l’addition|Symbole',1],['CUIRE','Passer au four|Faire chauffer',1],
['DANSE','On la fait en musique|Valse ou tango',1],['DEBUT','Le contraire de la fin|Commencement',1],
['DENTS','Elles mordent|Elles croquent',1],['DESSUS','x',1],['DOIGT','Il y en a cinq par main|Pouce ou index',1],
['DOUZE','Après onze|Une douzaine',1],['DRAME','Pièce très sérieuse|Catastrophe',2],
['ECHEC','Contraire de la réussite|Jeu de dames et de rois',2],['ECOLE','On y apprend à lire|Établissement',1],
['ECRAN','Il affiche l’image|Il fait obstacle',1],['ELEVE','Il apprend à l’école|Il monte',1],
['EPICE','Elle relève les plats|Poivre ou cumin',2],['ETAGE','Niveau d’immeuble|Palier',1],
['ETANG','Petit lac|Plan d’eau',2],['ETOFFE','x',2],['FACON','Manière|Style',2],
['FERME','Maison des vaches|Solide|Elle clôt',1],['FETES','Réjouissances|Noël en fait partie',1],
['FEUIL','x',3],['FILLE','Enfant féminin|Jeune femme',1],
['FLEUR','Elle sent bon au jardin|Rose ou tulipe',1],['FOIRE','Grand marché|Fête foraine',2],
['FORET','Beaucoup d’arbres|Bois épais',1],['FORME','Contour|Bonne condition',1],
['FOULE','Beaucoup de monde|Multitude',1],['FRERE','Fils des mêmes parents|Moine',1],
['FRUIT','Pomme ou poire|Résultat',1],['FUMEE','Elle sort de la cheminée|Signe du feu',1],
['FUSEE','Elle part vers l’espace|Engin spatial',1],['GANTS','Ils couvrent les mains|Protection',1],
['GARDE','Surveillance|Sentinelle',1],['GENOU','Articulation de la jambe|On s’y agenouille',1],
['GLACE','Dessert froid|Miroir|Eau gelée',1],['GOMME','Elle efface le crayon|Caoutchouc',1],
['GOUTS','Saveurs|Préférences',2],['GRAIN','Petite graine|Averse soudaine',2],
['GRAND','De grande taille|Important',1],['GROUPE','x',1],['GUIDE','Il montre le chemin|Manuel',1],
['HACHE','Elle fend le bois|Outil du bûcheron',2],['HERBE','Verte, dans le pré|Gazon',1],
['HEURE','Soixante minutes|Moment',1],['HIVER','Saison la plus froide|Saison de la neige',1],
['HOMME','Être humain|Monsieur',1],['HOTEL','On y dort en voyage|Établissement',1],
['HUILE','Elle graisse|Olive ou tournesol',1],['IDEAL','Parfait|Rêvé',2],
['IDEES','Pensées|Projets',1],['IGLOO','Maison de glace|Abri esquimau',2],
['IMAGE','Photo ou dessin|Reflet',1],['INDEX','Doigt qui montre|Liste alphabétique',2],
['JAMBE','Elle porte le corps|Membre inférieur',1],['JARRE','Grand pot de terre|Vase antique',3],
['JETON','Pièce de jeu|Marque',2],['JEUDI','Après mercredi|Jour de la semaine',1],
['JOUER','Ce que font les enfants|S’amuser|Interpréter',1],['JOURS','Journées|Le temps qui passe',1],
['JUPON','Sous la jupe|Jupe de dessous',3],['JUSTE','Équitable|Exact|À peine assez',2],
['LAINE','Elle vient du mouton|Fil du pull',1],['LAMPE','Elle éclaire la pièce|Ampoule',1],
['LARME','Elle coule quand on pleure|Goutte',1],['LEVRE','Bord de la bouche|Elle embrasse',2],
['LIGNE','Trait droit|Rangée|Silhouette',1],['LIONS','Fauves à crinière|Rois des animaux',1],
['LIVRE','Il se lit page après page|Ouvrage|Ancienne monnaie',1],['LUNDI','Début de semaine|Après dimanche',1],
['MAINS','Elles serrent|Elles applaudissent',1],['MAIRE','Chef de la commune|Il porte l’écharpe',2],
['MARIN','Homme des bateaux|Du bord de mer',1],['MELON','Fruit sucré de l’été|Chapeau rond',1],
['MERCI','Mot de politesse|Remerciement',1],['MIDIS','x',3],
['MONDE','La Terre entière|Les gens',1],['MOTIF','Dessin répété|Raison',2],
['MUSEE','On y voit des tableaux|Le Louvre en est un',1],['NAGER','Se déplacer dans l’eau|Faire des longueurs',1],
['NAVET','Légume racine|Mauvais film',2],['NEIGE','Blanche, elle tombe en hiver|Poudreuse',1],
['NOEUD','On le fait avec une corde|Il se serre',2],['NOMBRE','x',1],
['NUAGE','Il cache parfois le soleil|Vapeur du ciel',1],['OCEAN','Vaste étendue d’eau salée|Atlantique',1],
['OLIVE','Petit fruit de l’apéritif|Verte ou noire',1],['OMBRE','Elle suit au soleil|Zone sans lumière',1],
['ONCLE','Frère du père|Il a des neveux',1],['ORAGE','Éclairs et tonnerre|Tempête',1],
['OSIER','Il tresse les paniers|Saule souple',3],['PAGES','Feuilles du livre|Elles se tournent',1],
['PAPIER','x',1],['PARIS','Capitale française|Enjeux de jeu',1],
['PARTS','Portions|Morceaux du gâteau',2],['PATES','Spaghettis et macaronis|Pâtisserie',1],
['PECHE','Fruit à noyau|Sport à la ligne|Faute',1],['PERLE','Bijou de l’huître|Erreur amusante',2],
['PETIT','De faible taille|Enfant',1],['PIANO','Instrument à touches|Doucement, en musique',1],
['PIECE','Salle de la maison|Monnaie|Théâtre',1],['PLAGE','Sable au bord de la mer|Étendue',1],
['PLUIE','Elle mouille|Averse',1],['POCHE','Elle est dans le pantalon|Sac',1],
['POIDS','Il se mesure en kilos|Charge',1],['POIRE','Fruit du poirier|Naïf',1],
['POMME','Fruit rouge ou vert|De terre',1],['PORTE','On la pousse pour entrer|Battant',1],
['POULE','Elle pond des œufs|Femelle du coq',1],['RADIO','On l’écoute pour la musique|Cliché médical',1],
['REGLE','Elle trace des traits|Loi|Norme',1],['REVER','Ce qu’on fait en dormant|Imaginer',1],
['REINE','Épouse du roi|Abeille pondeuse|Carte',1],['RIVES','Bords du fleuve|Berges',2],
['RONDE','Forme du cercle|Danse|Patrouille',1],['ROUGE','Couleur du sang|Vin|Feu de stop',1],
['ROUTE','Les voitures y roulent|Chemin',1],['RUCHE','Maison des abeilles|Lieu très actif',2],
['SABLE','Grains de la plage|Dune',1],['SALLE','Grande pièce|Auditoire',1],
['SAUCE','Elle accompagne le plat|Jus lié',1],['SEULE','Sans personne|Unique',1],
['SIEGE','On s’y assoit|Blocus|Lieu principal',2],['SIROP','Sucré, à diluer|Médicament liquide',1],
['SOEUR','Fille des mêmes parents|Religieuse',1],['SOLEIL','x',1],
['SPORT','Activité physique|Foot ou tennis',1],['SUCRE','Il adoucit le café|Doux',1],
['TABLE','Meuble à quatre pieds|Liste de données',1],['TAPIS','Il couvre le sol|Moquette',1],
['TEMPS','Il passe|Météo|Durée',1],['TERRE','Notre planète|Sol|Argile',1],
['TIGRE','Grand félin rayé|Fauve du Bengale',1],['TIMBRE','x',2],
['TOILE','Tissu|Tableau|De l’araignée',1],['TRAIN','Il roule sur des rails|Convoi|Allure',1],
['TROIS','Après deux|Chiffre',1],['USAGE','Manière de se servir|Coutume',2],
['USINE','Bâtiment où on fabrique|Manufacture',1],['UTILE','Qui sert à quelque chose|Pratique',1],
['UNION','Fait la force|Mariage|Alliance',2],['VACHE','Elle donne le lait|Elle meugle',1],
['VAGUE','Elle vient de la mer|Imprécise|Houle',1],['VELOS','Bicyclettes|Deux-roues',1],
['VENTS','Souffles|Ils gonflent les voiles',2],['VERRE','On y boit de l’eau|Matière transparente',1],
['VERTE','Couleur de l’herbe|Pas mûre',1],['VILLE','Plus grande qu’un village|Agglomération',1],
['VIVRE','Être en vie|Exister',1],['VOILE','Elle pousse le bateau|Tissu qui cache',1],
['VOTER','Mettre son bulletin|Élire',2],['ZEBRE','Cheval rayé|Individu bizarre',2],
].filter(w => w[1] !== 'x');

const W6 = [
['ABEILLE','x',1],['AGNEAU','Petit du mouton|Il bêle',1],['AIGUILLE','x',2],
['AMANDE','Fruit sec du nougat|Elle est dans la coque',2],['ANIMAL','Le chien en est un|Bête',1],
['ARGENT','Métal précieux|Monnaie',1],['ARRIVE','Il parvient au but|Il survient',2],
['ARTIST','x',2],['AUTEUR','Il écrit des livres|Créateur',2],
['AUTOMNE','x',1],['AVOCAT','Fruit vert|Homme de loi',2],
['BALCON','Terrasse en hauteur|Étage du théâtre',1],['BALLON','On y joue au foot|Il se gonfle',1],
['BANANE','Fruit jaune du singe|Elle se pèle',1],['BATEAU','Il navigue sur l’eau|Navire',1],
['BEURRE','Il tartine le pain|Il vient de la crème',1],['BONBON','Sucrerie des enfants|Friandise',1],
['BOUCHE','Elle mange et parle|Elle sourit',1],['BOUTON','Il ferme la chemise|Il s’appuie|Sur la peau',1],
['BUREAU','Meuble pour travailler|Lieu de travail',1],['CAMION','Gros véhicule|Poids lourd',1],
['CANARD','Oiseau de la mare|Journal, familièrement',1],['CARTON','Boîte de déménagement|Papier épais',1],
['CASIER','Rangement à cases|Piège à homards',2],['CERISE','Petit fruit rouge à noyau|Sur le gâteau',1],
['CHEVAL','On le monte en selle|Il hennit',1],['CHEMIN','Voie de campagne|Sentier',1],
['CIRQUE','Il a des clowns|Chapiteau|Vallée en montagne',1],['CLAVIER','x',2],
['COIFFE','Elle couvre la tête|Elle arrange les cheveux',3],['COLLINE','x',2],
['COUTEAU','x',1],['CRAYON','Il écrit et s’efface|Il se taille',1],
['CUILLERE','x',1],['CUISSE','Haut de la jambe|Morceau du poulet',2],
['DANGER','Il faut s’en méfier|Péril',1],['DESSIN','Fait au crayon|Croquis',1],
['DIMANCHE','x',1],['DOCTEUR','x',2],['DOMINO','Petit rectangle à points|Jeu de table',2],
['DOUCHE','On s’y lave debout|Averse',1],['ECLAIR','Il zèbre le ciel|Gâteau au chocolat|Très rapide',1],
['ECOLES','Établissements scolaires',1],['ENFANT','Il n’est pas encore adulte|Petit',1],
['EPAULE','Entre le cou et le bras|Morceau d’agneau',1],['ESCALE','Arrêt du voyage|Halte du navire',2],
['ETOILE','Elle brille dans la nuit|Vedette',1],['FACILE','Le contraire de difficile|Aisé',1],
['FERMER','Le contraire d’ouvrir|Clore',1],['FLACON','Petite bouteille|De parfum',2],
['FLEUVE','Il se jette dans la mer|Grande rivière',1],['FRAISE','Fruit rouge du printemps|Outil du dentiste',1],
['FUSION','Passage à l’état liquide|Union de sociétés',3],['GARAGE','Abri de la voiture|Atelier de réparation',1],
['GARCON','Enfant masculin|Serveur du café',1],['GATEAU','Dessert d’anniversaire|Pâtisserie',1],
['GLACON','Cube froid dans le verre|Il fond',1],['GRAINE','On la sème|Semence',1],
['GRANGE','Bâtiment de la ferme|On y range le foin',2],['GUITARE','x',1],
['HAMEAU','Tout petit village|Groupe de maisons',3],['HANCHE','Haut de la jambe|Elle porte la ceinture',2],
['HOMARD','Crustacé à grosses pinces|Il devient rouge cuit',2],['HUMEUR','Bonne ou mauvaise|État d’esprit',2],
['IMPACT','Choc|Effet produit',2],['INDICE','Il met sur la piste|Signe|Nombre repère',2],
['ISOLER','Mettre à part|Protéger du froid',2],['JARDIN','On y cultive des fleurs|Potager',1],
['JAUNIR','Devenir jaune|Vieillir, pour le papier',2],['JOUEUR','Il participe à la partie|Il aime parier',1],
['JUMEAU','Né le même jour|Identique',2],['LANCER','Jeter au loin|Débuter|Épreuve d’athlétisme',1],
['LEGUME','La carotte en est un|Il pousse au potager',1],['LEZARD','Petit reptile au soleil|Il fait la sieste',2],
['LOUTRE','Elle nage dans la rivière|Mammifère à fourrure',2],['LUMIERE','x',2],
['MAISON','On y habite|Demeure',1],['MANTEAU','x',1],['MARCHE','On y achète des légumes|Escalier|Il avance',1],
['MELODIE','x',2],['MIROIR','On s’y regarde|Glace',1],
['MINUTE','Soixante secondes|Un instant',1],['MOUTON','Il donne la laine|Il bêle|Vague blanche',1],
['MUSCLE','Il fait bouger le corps|Biceps',2],['NATURE','Forêts et rivières|Sans additif|Caractère',1],
['NAVIRE','Grand bateau|Vaisseau',1],['NOMBRE','Le sept en est un|Quantité',1],
['NOUGAT','Confiserie aux amandes|Spécialité de Montélimar',3],['NUAGES','Ils cachent le soleil|Ils annoncent la pluie',1],
['OISEAU','Il a des plumes|Il fait son nid',1],['OLIVES','Fruits de l’apéritif|Elles donnent l’huile',1],
['ORANGE','Fruit et couleur|Agrume|Feu de prudence',1],['OUTILS','Marteau et tournevis|Instruments',1],
['PANIER','On y met les courses|But au basket',1],['PLANTE','Elle pousse dans un pot|Dessous du pied',1],
['POISON','Substance mortelle|Venin',2],['POISSON','x',1],['PRINCE','Fils du roi|Souverain',1],
['RACINE','Partie de l’arbre sous terre|Origine|Carrée en maths',1],['RENARD','Rusé, à la queue rousse|Goupil',1],
['RIVAGE','Bord de la mer|Littoral',2],['ROSIER','Arbuste à roses|Il a des épines',2],
['SAVANE','Plaine des lions|Herbe d’Afrique',2],['SIRENE','Femme-poisson des légendes|Alarme sonore',2],
['SOLEIL','Il éclaire le jour|Astre du jour',1],['SOURIS','Petit rongeur|Objet d’ordinateur',1],
['TIROIR','Il se tire du meuble|Compartiment',1],['TOMATE','Rouge, dans la salade|Fruit du potager',1],
['TRESOR','Coffre des pirates|Grande richesse',1],['TUNNEL','Passage sous la terre|Galerie',1],
['UNIQUE','Il n’y en a qu’un|Exceptionnel',2],['UNITES','Éléments comptés un à un|Chiffres de droite',3],
['URGENT','Qui ne peut pas attendre|Pressant',2],['VERGER','Champ d’arbres fruitiers|Pommeraie',2],
['VILLES','Agglomérations|Cités',1],['VIOLON','Instrument à archet|Il a quatre cordes',1],
['VOISIN','Il habite à côté|Proche',1],['VOYAGE','Départ vers ailleurs|Périple',1],
].filter(w => w[1] !== 'x');

const W7 = [
['ABEILLE','Elle fait le miel|Insecte de la ruche',1],['AMANDES','Fruits secs du nougat|Dans les coques',2],
['ANCETRE','Aïeul lointain|Il précède',3],['ANIMAUX','Le zoo en est plein|Bêtes',2],
['ARTISTE','Peintre ou musicien|Créateur',2],['AUTOMNE','Saison des feuilles mortes|Après l’été',1],
['BALCONS','Terrasses en hauteur|Ils dominent la rue',2],['BANQUET','Grand repas de fête|Festin',3],
['BISCUIT','Petit gâteau sec|Il croque',2],['BOUTIQUE','x',2],
['BRIGADE','Équipe d’intervention|Groupe de gendarmes',3],['CAMPING','Vacances sous la tente|Terrain de loisirs',2],
['CHANSON','On la chante|Refrain et couplets',2],['CHATEAU','Demeure du roi|Il a des tours|Vin de Bordeaux',2],
['CHEMISE','Vêtement à boutons|Dossier de papier',2],['CLAVIER','Il a des touches|Du piano ou de l’ordinateur',2],
['COLLINE','Petite montagne|Élévation douce',2],['COUTEAU','Il coupe la viande|Lame et manche',1],
['CUISINE','Pièce des casseroles|Art des plats',2],['DESSERT','Fin du repas|Gâteau ou fruit',2],
['DIAMANT','Pierre très précieuse|Il raye le verre',2],['DOCTEUR','Il soigne les malades|Médecin',2],
['DRAGONS','Ils crachent le feu|Créatures des légendes',2],['ECLAIRS','Ils zèbrent le ciel|Gâteaux au chocolat',2],
['EMOTION','Ce que le cœur ressent|Trouble',3],['EPINARD','Légume vert de Popeye|Feuille du potager',3],
['ETAGERE','Planche pour les livres|Rayonnage',3],['FALAISE','Haute paroi au bord de mer|Roche à pic',3],
['FAUTEUIL','x',2],['FENETRE','Elle laisse entrer le jour|Ouverture vitrée',2],
['FORTUNE','Grande richesse|Chance',3],['FROMAGE','Il se fait avec du lait|Camembert ou comté',2],
['GALETTE','On y cache une fève|Crêpe de sarrasin',3],['GARDIEN','Il surveille|Il arrête les tirs',2],
['GLACIER','Fleuve de glace|Marchand de glaces',3],['GRENIER','Sous le toit|On y monte les vieilleries',3],
['GUITARE','Instrument à six cordes|On en gratte les cordes',1],['HARICOT','Vert, il se mange|Légume en gousse',2],
['HAUTEUR','Distance vers le haut|Altitude|Arrogance',3],['HORLOGE','Elle donne l’heure|Pendule',2],
['IMMENSE','Très très grand|Illimité',3],['INSECTE','La fourmi en est un|Il a six pattes',2],
['INVITES','Ils viennent à la fête|Conviés',2],['ISOLOIR','Cabine pour voter|Il assure le secret',3],
['JARDINS','Espaces verts cultivés|Parcs',2],['JOURNAL','On y lit les nouvelles|Quotidien|Carnet intime',2],
['JOYEUSE','Pleine de gaieté|Enjouée',3],['JUMELLE','Sœur née le même jour|Identique',3],
['LEZARDS','Reptiles des vieux murs|Ils lézardent au soleil',3],['LIBERTE','Devise avec égalité|Indépendance',2],
['LOTERIE','Jeu de tirage au sort|Hasard',3],['LUMIERE','Elle chasse le noir|Clarté|Génie',2],
['MACHINE','Elle fonctionne toute seule|Appareil',2],['MANTEAU','Vêtement d’hiver|Il couvre',1],
['MARTEAU','Il enfonce les clous|Outil du charpentier',2],['MELODIE','Suite de notes|Air chantant',2],
['MONTAGE','Assemblage des images|Installation',3],['MUSIQUE','Art des sons|On l’écoute',2],
['NAVIRES','Bateaux de haute mer|Flotte',2],['NECTARS','Boissons des dieux|Jus sucrés',3],
['NOISETTE','x',2],['NOUVEAU','Qui vient d’arriver|Récent|Novice',2],
['NUMEROS','Chiffres des maisons|Tours de cirque',2],['OCTOBRE','Mois des feuilles mortes|Après septembre',2],
['ORANGER','Arbre à agrumes|Fleur de mariée',3],['OREILLE','Elle entend|Anse du panier',2],
['OUVRAGE','Travail soigné|Livre',3],['PEINTRE','Il tient un pinceau|Artiste des couleurs',2],
['PIRATES','Bandits des mers|Ils ont un drapeau noir',2],['POISSON','Il nage avec des nageoires|Avril lui est dédié',1],
['POTAGER','Jardin de légumes|Carré de terre',3],['PRAIRIE','Grand pré|Herbe des vaches',3],
['RECOLTE','Ramassage des cultures|Moisson',3],['RENARDS','Rusés du bois|Goupils',2],
['RIVIERE','Elle coule vers le fleuve|Cours d’eau|Collier de diamants',2],['ROULEAU','Il sert à peindre|Vague qui déferle',3],
['SARDINE','Petit poisson en boîte|Piquet de tente',3],['SEMAINE','Elle a sept jours|Du lundi au dimanche',2],
['SILENCE','Absence de bruit|Pause en musique',2],['SOURIRE','Signe de bonne humeur|Il éclaire le visage',2],
['THEATRE','On y joue des pièces|Scène|Lieu des opérations',2],['TOITURE','Ensemble du toit|Couverture',3],
['TORTUES','Elles portent leur maison|Elles sont lentes',2],['TRAJETS','Chemins parcourus|Parcours',3],
['UNIVERS','Tout le cosmos|Monde entier',2],['URGENCE','Cas à traiter vite|Service de l’hôpital',3],
['USAGERS','Ceux qui utilisent le service|Clients',3],['USINAGE','Façonnage des pièces|Travail du métal',3],
['VERGERS','Champs de pommiers|Plantations fruitières',3],['VILLAGE','Plus petit qu’une ville|Bourg',2],
['VOITURE','Elle a quatre roues|Automobile',2],['VOYAGES','Déplacements lointains|Périples',2],
].filter(w => w[1] !== 'x');

const W8 = [
['AVENTURE','Épopée risquée|Péripétie',2],['BAGUETTE','Pain long|Du chef d’orchestre',2],
['BOUTEILLE','x',2],['BOUTIQUE','Petit magasin|Échoppe',2],
['CAMPAGNE','Elle s’oppose à la ville|Opération militaire|Électorale',2],['CHAMPION','Vainqueur|Le meilleur',2],
['CHEMINEE','Le Père Noël y passe|Conduit de fumée',2],['COMPTOIR','Bar du café|Table de vente',3],
['CROISADE','Expédition médiévale|Campagne militante',3],['CUILLERE','Elle sert la soupe|Couvert creux',1],
['DIMANCHE','Jour de repos|Fin de semaine',1],['DRAPEAUX','Emblèmes des pays|Ils flottent au vent',2],
['ESCALIER','On le monte marche à marche|Il mène à l’étage',2],['FAUTEUIL','Siège confortable|Il a des accoudoirs',2],
['FONTAINE','Elle donne de l’eau|Bassin de la place',2],['GRENOUILLE','x',2],
['HERISSON','Il a des piquants|Il se met en boule',2],['HISTOIRE','Récit du passé|Conte',2],
['JONQUILLE','x',3],['LANTERNE','Lampe portative|Feu arrière',3],
['MONTAGNE','Elle a des sommets|Les Alpes en sont',1],['MORCEAUX','Fragments|Airs de musique',2],
['NOISETTE','Fruit du noisetier|Couleur des yeux',2],['OMELETTE','Œufs battus à la poêle|Plat rapide',2],
['ORCHIDEE','Fleur exotique|Plante délicate',3],['PAPILLON','Il sort de la chrysalide|Nage|Contravention',1],
['PEINTURE','Art des couleurs|Elle recouvre le mur',2],['PLANCHER','Sol de la pièce|Il grince',2],
['PORTRAIT','Il représente le visage|Description',2],['PRINCESSE','x',2],
['RESTAURANT','x',2],['ROULETTE','Petite roue|Jeu du casino|Du dentiste',3],
['SANGLIER','Cochon sauvage|Il fouille la terre',3],['SEMELLE','x',2],
['TABLEAUX','Œuvres peintes|Panneaux d’affichage',2],['TROMPETTE','x',2],
['VACANCES','Congés d’été|Repos scolaire',1],['VENDREDI','Avant samedi|Fin de semaine de travail',1],
['VOISINAGE','x',3],['ZEPHYR','x',3],
].filter(w => w[1] !== 'x');

// ---------------------------------------------------------------------
//  Index et utilitaires
// ---------------------------------------------------------------------
const LISTS = { 3: W3, 4: W4, 5: W5, 6: W6, 7: W7, 8: W8 };

// Normalise : ['MOT','d1|d2',n] -> { m, defs:[...], n }
function normalize(lists) {
    const out = {};
    for (const [len, list] of Object.entries(lists)) {
        out[len] = list
            .filter(([m]) => m.length === +len)          // garde-fou : longueur exacte
            .map(([m, d, n]) => ({ m, defs: String(d).split('|').filter(Boolean), n }));
    }
    return out;
}
const WORDS = normalize(LISTS);

function buildIndex(words) {
    const idx = {};
    for (const [len, list] of Object.entries(words)) {
        idx[len] = {};
        for (const w of list) (idx[len][w.m[0]] = idx[len][w.m[0]] || []).push(w);
    }
    return idx;
}

module.exports = {
    WORDS,                                   // { longueur: [ {m, defs, n} ] }
    INDEX: buildIndex(WORDS),                // { longueur: { initiale: [...] } }
    all: () => Object.values(WORDS).flat(),
};