// =====================================================================
//  MOTS FLÉCHÉS — extension du dictionnaire.
//  Même format : ['MOT', 'déf 1|déf 2', niveau]  (1 courant · 2 moyen · 3 rare)
//  Ces listes sont fusionnées automatiquement avec words.js.
// =====================================================================

const X4 = [
['ABBE','Homme d’Église|Supérieur du monastère',3],['ACRE','Piquant au goût|Ancienne mesure agraire',3],
['AGIR','Passer à l’action|Faire effet',1],['ALPE','Sommet, en poésie|Pâturage de montagne',3],
['ANIS','Graine parfumée|Il aromatise la boisson',3],['APRE','Rude|Âpre au gain',3],
['AVAL','En bas de la rivière|Accord donné',2],['AVEU','Confession|Reconnaissance d’une faute',2],
['AXES','Lignes de symétrie|Grandes orientations',2],['BAIN','On le prend dans la baignoire|Immersion',1],
['BLES','Céréales du pain|Champs dorés',2],['BOND','Saut brusque|Progression rapide',2],
['BRIN','Petit morceau|D’herbe',2],['CANE','Femelle du canard|Elle barbote',2],
['CENT','Après quatre-vingt-dix-neuf|Centaine',1],['CHUT','Ordre de se taire|Silence !',2],
['CIME','Sommet de l’arbre|Point culminant',2],['CLAN','x',2],
['CLOU','Le marteau l’enfonce|Attraction principale',1],['CODE','Suite de chiffres secrète|Règlement',1],
['COTE','Bord de mer|Os du thorax|Pente',1],['CRAN','Courage|Encoche',3],
['CUVE','Grand récipient|Elle sert à la vinification',3],['DEUX','Après un|Une paire',1],
['DINDE','x',1],['DIRE','Prononcer|Exprimer',1],
['DOUX','x',1],['DRAP','Il couvre le lit|Toile de coton',1],
['ECHU','Arrivé à terme|Expiré',3],['ELUS','Ils ont été votés|Choisis',2],
['EPEE','Arme du mousquetaire|Lame longue',2],['ETAU','Il serre la pièce|Pression',3],
['FAIM','Envie de manger|Appétit',1],['FAUX','Contraire de vrai|Outil du faucheur',1],
['FLOT','Vague|Grande quantité',2],['FOLIE','x',2],
['FOUET','x',2],['FUIR','S’échapper|Perdre son eau',1],
['GAIE','Joyeuse|De bonne humeur',2],['GITE','Logement rural|Morceau de bœuf',3],
['GRES','Roche dure|Poterie vernissée',3],['HALL','Grande entrée|Vestibule',2],
['HERO','x',3],['HUIS','Porte, en vieux français|À huis clos',3],
['IVRE','Il a trop bu|Enivré',2],['JADE','Pierre verte d’Asie|Bijou précieux',3],
['LAIE','Femelle du sanglier|Sentier forestier',3],['LARD','Gras du porc|Il fume la soupe',2],
['LEGS','Ce qu’on laisse en héritage|Donation',3],['LIEU','Endroit|Poisson blanc',1],
['LOTS','Parts d’un partage|Prix de tombola',2],['LUTH','Instrument à cordes ancien|Ancêtre de la guitare',3],
['MARE','Petit étang|Flaque des canards',2],['MENU','Liste des plats|Tout petit',1],
['MIME','Il joue sans parler|Artiste silencieux',2],['MOIS','x',1],
['MUET','Il ne parle pas|Silencieux',2],['NAIF','Trop confiant|Candide',2],
['NEUF','x',1],['NOIX','Fruit à coque|Cerneau',1],
['ODES','Poèmes lyriques|Chants d’éloge',3],['ORME','Grand arbre des allées|Bois dur',3],
['PAVE','Pierre de la rue|Gros livre',2],['PEUR','Sensation d’effroi|Crainte',1],
['PILE','Elle donne du courant|Tas|Côté de la pièce',1],['PLIS','Marques du tissu|Rides',2],
['POIS','Légume vert rond|Motif de la robe',2],['PUCE','Insecte sauteur|Composant électronique',2],
['QUOI','Pronom interrogatif|Comment ?',2],['RAID','Expédition sportive|Attaque rapide',3],
['RAIS','Rayons, en poésie|Traits de lumière',3],['RANG','Place dans la file|Position',1],
['RIDE','Marque du visage|Pli de l’eau',2],['ROTI','Viande cuite au four|Grillé',1],
['SAIN','En bonne santé|Bon pour le corps',1],['SAUF','Excepté|Hors de danger',2],
['SCIE','Elle coupe le bois|Rengaine',1],['SEVE','x',2],
['SOIN','Attention portée|Traitement',1],['SUIE','Noir de la cheminée|Résidu de fumée',3],
['TALC','Poudre blanche|Il assèche',3],['TAON','Grosse mouche qui pique|Insecte du bétail',3],
['TIRS','Coups au but|Épreuves de précision',2],['TOME','Volume d’une série|Livre numéroté',2],
['TRAC','Peur avant d’entrer en scène|Angoisse',2],['TROC','Échange sans argent|Commerce ancien',3],
['USER','Détériorer par l’usage|Se servir de',2],['VEAU','Petit de la vache|Viande blanche',1],
['VENU','Arrivé|Il est là',2],['VERT','Couleur de l’herbe|Écologique|Pas mûr',1],
['VOEU','Souhait|Promesse solennelle',2],['ZINC','Métal du toit|Comptoir du bar',3],
].filter(w => w[1] !== 'x');

const X5 = [
['ADEPT','x',3],['AGATE','Pierre semi-précieuse|Bille de verre',3],
['AIGRE','Acide au goût|Ton désagréable',2],['AISLE','x',3],
['ALBUM','Il range les photos|Disque',1],['ALGUE','Plante de la mer|Verte sur les rochers',2],
['ALLIE','Partenaire|Ami dans la guerre',2],['AMPLE','Large|Vaste',2],
['ANCRE','Elle retient le bateau|Elle mord le fond',2],['ANNEAU','x',2],
['APPUI','Soutien|Point d’équilibre',2],['ARDRE','x',3],
['ARMES','Épées et fusils|Blason',2],['AROME','Parfum du café|Senteur',2],
['ASILE','Refuge|Protection accordée',3],['ASTRE','Étoile ou planète|Corps céleste',2],
['ATOUT','Carte maîtresse|Avantage',2],['AUBES','Levers du jour|Aurores',3],
['AUCUN','Pas un seul|Nul',2],['AVARE','Il compte ses sous|Pingre',2],
['AVEUX','Confessions|Reconnaissances',2],['BACHE','Toile de protection|Elle couvre le camion',2],
['BAGNE','Prison des travaux forcés|Lieu très dur',3],['BARGE','Bateau à fond plat|Oiseau des marais',3],
['BASSE','Note grave|Peu élevée',2],['BEURRE','x',1],
['BIAIS','De travers|Moyen détourné',3],['BIERE','Boisson à la mousse|Cercueil',1],
['BISON','Gros bovin d’Amérique|Il broute la prairie',2],['BLAME','Reproche officiel|Sanction',3],
['BOEUF','Gros bovin|Viande rouge',1],['BOMBE','Engin explosif|Chapeau de cavalière',2],
['BORNE','Limite|Pierre du chemin',2],['BOUES','Terres détrempées|Soins thermaux',3],
['BRUME','Brouillard léger|Voile du matin',2],['BUCHE','Bois de la cheminée|Gâteau de Noël',1],
['CABAS','Sac du marché|Panier souple',3],['CACAO','Poudre du chocolat|Fève tropicale',1],
['CADET','Le plus jeune|Élève officier',2],['CAGES','Elles enferment les oiseaux|Prisons',2],
['CALME','Sans agitation|Tranquille',1],['CANOT','Petite embarcation|Barque à rames',2],
['CAPES','Manteaux sans manches|Elles volent au vent',3],['CARIE','Trou dans la dent|Le dentiste la soigne',2],
['CASQUE','x',1],['CEDRE','Grand conifère|Arbre du Liban',3],
['CHAOS','Grand désordre|Confusion totale',2],['CHARM','x',3],
['CHUTE','Elle fait tomber|Cascade|Fin de l’histoire',1],['CIGAL','x',3],
['CIVET','Ragoût de lièvre|Plat mijoté',3],['CLOUS','x',2],
['COBRA','Serpent à lunettes|Reptile venimeux',2],['COMTE','Titre de noblesse|Fromage du Jura',2],
['CONTE','Histoire pour enfants|Récit merveilleux',1],['CORAL','x',3],
['COTON','Fibre du tee-shirt|Il pousse en boule',1],['CRANE','Os de la tête|Il protège le cerveau',2],
['CREUX','Vide à l’intérieur|Cavité',2],['CROC','x',2],
['CRUEL','Sans pitié|Féroce',2],['CUBES','Jeux de l’enfant|Volumes à six faces',2],
['CYGNE','Grand oiseau blanc|Il glisse sur le lac',2],['DEDIE','Consacré à|Offert',3],
['DEFIS','Challenges|Provocations',2],['DELTA','Embouchure du fleuve|Lettre grecque',3],
['DENSE','Serré|Épais',2],['DEPOT','Lieu de stockage|Sédiment',2],
['DIGUE','Elle retient la mer|Barrage',2],['DINDE','Volaille de Noël|Grosse poule',1],
['DIVAN','Canapé sans dossier|Lit du psy',3],['DOGME','Vérité imposée|Croyance rigide',3],
['DUNES','Collines de sable|Elles bordent la plage',2],['ECAILLE','x',2],
['ECLAT','Brillance|Morceau détaché|Scandale',2],['ECURIE','x',2],
['EMAIL','Il couvre la dent|Message électronique',2],['EMPIRE','x',2],
['ENGIN','Machine|Véhicule spécial',2],['ENNUI','Manque d’intérêt|Problème',2],
['ENVIE','Désir|Convoitise',1],['EPAVE','Bateau naufragé|Ruine',3],
['EPINE','Piquant de la rose|Ennui',2],['ESSAI','Tentative|Au rugby|Texte réflexif',2],
['ETAIN','Métal gris de la vaisselle|Alliage du bronze',3],['ETAUX','Outils qui serrent|Pinces d’atelier',3],
['EVIER','On y lave la vaisselle|Bac de la cuisine',2],['FAGOT','Bois lié en botte|Petit bois',3],
['FARCE','Blague|Garniture du volaille',2],['FAUNE','Les animaux d’un lieu|Divinité des bois',2],
['FIBRE','Filament|Internet rapide',2],['FIGUE','Fruit sucré du Sud|Elle sèche au soleil',2],
['FIOLE','Petit flacon|Éprouvette',3],['FLANC','Côté du corps|Versant',2],
['FLUTE','Instrument à vent|Verre à champagne|Pain fin',1],['FOLIE','Déraison|Extravagance',2],
['FOUET','Il bat les œufs|Lanière du cocher',2],['FOYER','Maison|Cheminée|Centre',2],
['FRAIS','Un peu froid|Dépenses',1],['FRANC','Sincère|Ancienne monnaie',2],
['GALON','Ruban décoratif|Marque du grade',3],['GAMME','Suite de notes|Éventail de produits',2],
['GEANT','Très grand|Colosse',1],['GENIE','Grande intelligence|Esprit des contes',2],
['GERBE','Bouquet de blé|Jet d’eau',3],['GIVRE','Glace du matin|Il blanchit les vitres',2],
['GLAND','Fruit du chêne|Ornement à franges',2],['GOLFE','Grande baie|Bras de mer',2],
['GORGE','Elle avale|Vallée étroite',2],['GRACE','Élégance|Pardon accordé',2],
['GRAVE','Sérieux|Son bas',1],['GREVE','Arrêt de travail|Bord de mer caillouteux',2],
['GRIFFE','x',2],['HALLE','Grand marché couvert|Bâtiment ouvert',3],
['HANGAR','x',2],['HAUTE','Élevée|De grande taille',1],
['HERON','Oiseau à long bec|Il pêche debout',2],['HIBOU','Rapace de nuit|Il hulule',1],
['HOULE','Mouvement de la mer|Vagues longues',3],['HUMBLE','x',2],
['HYENE','Charognard d’Afrique|Elle ricane',3],['IMPOT','On le paie à l’État|Taxe',2],
['INDES','Pays lointain d’Asie|Route des épices',3],['JAUGE','Elle mesure le niveau|Indicateur',3],
['JOUET','Objet de l’enfant|Il amuse',1],['JUGES','Ils rendent la justice|Arbitres',2],
['LAPIN','Il a de grandes oreilles|Il creuse un terrier',1],['LASSO','Corde du cow-boy|Nœud coulant',2],
['LATIN','Langue de Rome|Ancienne langue',2],['LIANE','Plante grimpante|Tarzan s’y accroche',2],
['LIMON','Terre fertile du fleuve|Sédiment',3],['LOBBY','x',3],
['LOGIS','Habitation|Demeure',3],['LOUVE','Femelle du loup|Elle allaita Romulus',3],
['LUGES','Traîneaux de neige|Elles glissent',2],['MAGIE','Art des sortilèges|Enchantement',1],
['MAILLE','x',2],['MANGE','Il se nourrit|Il dévore',1],
['MARGE','Bord de la page|Bénéfice',2],['MASSE','Grande quantité|Gros marteau',2],
['MATIN','Début de la journée|Avant midi',1],['MEUTE','Groupe de chiens|Foule menaçante',3],
['MIETTE','x',2],['MOINE','Religieux du monastère|Il vit en communauté',2],
['MORSE','Gros mammifère marin|Alphabet à points',3],['MOTEUR','x',1],
['MOUCHE','x',1],['NACRE','Intérieur brillant du coquillage|Reflet irisé',3],
['NAINE','Toute petite|Étoile peu lumineuse',2],['NAPPE','Elle couvre la table|Étendue souterraine',1],
['NOBLE','De haute naissance|Généreux',2],['NORME','Règle établie|Standard',2],
['NOTES','Elles se jouent|Résultats scolaires',1],['OASIS','Verdure du désert|Havre de paix',2],
['OBUS','x',3],['OMBRE','x',1],
['ONCLE','x',1],['ORTIE','Herbe qui pique|Elle brûle la peau',2],
['OTAGE','Personne retenue|Prisonnier d’échange',3],['OUEST','Où le soleil se couche|Point cardinal',1],
['PAGNE','Vêtement tropical|Étoffe nouée',3],['PALAIS','x',2],
['PARFUM','x',1],['PATIN','Il glisse sur la glace|Chausson de patinage',2],
['PAUSE','Petit arrêt|Repos',1],['PEDALE','x',1],
['PENTE','Terrain incliné|Descente',2],['PERCHE','Longue tige|Poisson de rivière',2],
['PESTE','Grande épidémie|Personne insupportable',3],['PETALE','x',2],
['PHARE','Il guide les navires|Lumière de la voiture',1],['PIANO','x',1],
['PISTE','Chemin de terre|Indice|Elle accueille les avions',1],['PIVOT','Axe de rotation|Point central',3],
['PLAIE','Blessure|Fléau',2],['PLOMB','Métal lourd|Fusible',2],
['POIVRE','x',1],['PORC','x',1],
['POSTE','Elle distribue le courrier|Emploi|Emplacement',1],['POUCE','Doigt le plus court|Mesure anglaise',1],
['PRUNE','Fruit violet à noyau|Amende, familièrement',1],['PUITS','Trou d’où on tire l’eau|Cavité profonde',1],
['PUPILLE','x',3],['QUEUE','Elle prolonge l’animal|File d’attente',1],
['RADAR','Il détecte les véhicules|Écho radio',2],['RAGES','Colères|Fureurs',2],
['RAMPE','Elle borde l’escalier|Plan incliné',2],['RAYON','Trait de lumière|Étagère du magasin|Du cercle',1],
['RECIF','Rocher sous la mer|Danger du navigateur',3],['REFUGE','x',2],
['REGNE','Durée du roi|Domaine du vivant',2],['REINS','Ils filtrent le sang|Bas du dos',2],
['REPAS','Déjeuner ou dîner|On le prend à table',1],['RESTE','Ce qui demeure|Différence',1],
['REVEIL','x',1],['RHUME','Nez qui coule|Petit refroidissement',1],
['ROCHE','Pierre dure|Matière du sol',1],['RONCE','Buisson qui pique|Elle donne les mûres',3],
['ROTIN','Fibre des fauteuils|Palmier grimpant',3],['ROUGE','x',1],
['RUBAN','Il noue les cheveux|Bande étroite',1],['RUINE','Bâtiment écroulé|Faillite',2],
['SABOT','Chaussure de bois|Pied du cheval',2],['SALON','Pièce de séjour|Foire commerciale',1],
['SAULE','Arbre pleureur|Il borde la rivière',2],['SEIGLE','x',3],
['SEPIA','Brun de l’encre ancienne|Teinte des vieilles photos',3],['SERRE','Abri des plantes|Il étreint',2],
['SEUIL','Entrée de la porte|Limite',2],['SIGNE','Geste|Symbole|Indice',1],
['SILEX','Pierre à feu|Roche de la préhistoire',3],['SINGE','Il grimpe aux arbres|Il imite',1],
['SOUCI','Inquiétude|Fleur orangée',1],['SOUCHE','x',3],
['SOUPE','Potage du soir|Bouillon de légumes',1],['STADE','Terrain de sport|Étape',1],
['SUCRE','x',1],['SUEUR','Transpiration|Effort',2],
['TACHE','Marque salissante|Travail à faire',1],['TAILLE','x',1],
['TALON','Arrière du pied|Il rehausse la chaussure',1],['TANTE','Sœur du père|Elle a des neveux',1],
['TAUPE','Elle creuse des galeries|Espion infiltré',2],['TEMPE','Côté du front|Zone du crâne',3],
['TENTE','Abri de camping|Elle se plante',1],['TERME','Fin|Mot précis|Échéance',2],
['TIGE','x',2],['TOILE','x',1],
['TORSE','Haut du corps|Buste',2],['TOTAL','Somme complète|Entier',1],
['TRACE','Marque laissée|Empreinte',1],['TRAIT','Ligne tirée|Caractéristique',1],
['TRIBU','Groupe familial|Clan',2],['TRONC','Corps de l’arbre|Boîte à offrandes',1],
['TROUPE','x',2],['TRUIE','Femelle du porc|Elle a des porcelets',3],
['TULIPE','x',1],['USURE','Détérioration par le temps|Intérêt excessif',3],
['VALSE','Danse à trois temps|Tourbillon',2],['VAPEUR','x',2],
['VEINE','Elle ramène le sang|Chance, familièrement',2],['VENIN','Poison du serpent|Méchanceté',2],
['VERGE','Baguette|Mesure anglaise',3],['VERNI','Recouvert de vernis|Chanceux',3],
['VESTE','Vêtement à manches|Échec, familièrement',1],['VIGNE','Elle donne le raisin|Plante du vin',1],
['VIRUS','Il rend malade|Programme nuisible',1],['VITRE','Verre de la fenêtre|Carreau',1],
['VOILE','x',1],['VOUTE','Plafond courbe|Arc de pierre',3],
].filter(w => w[1] !== 'x');

const X6 = [
['ABEILLE','x',1],['ABSENT','Pas là|Manquant',1],['ACCENT','Signe sur la lettre|Manière de parler',2],
['ACHATS','Courses|Emplettes',1],['ACTEUR','Il joue la comédie|Comédien',1],
['AFFAIRE','x',2],['AIGUILLE','x',2],['ALBUMS','Recueils de photos|Disques',2],
['ALLURE','Vitesse|Élégance du maintien',2],['AMANDE','x',2],
['AMITIE','Lien entre amis|Affection',1],['ANCRES','Elles retiennent les navires',2],
['ANNEAU','Bague|Cercle de métal',2],['ARCADE','Passage voûté|Au-dessus de l’œil',3],
['ARDOISE','x',2],['ARMOIRE','x',1],['ARROSER','x',1],
['ATELIER','x',2],['AUBAINE','x',3],['AUTOUR','Tout près|Rapace diurne',2],
['AVENIR','Ce qui vient|Futur',1],['AVERSE','Pluie soudaine|Ondée',2],
['BAGAGE','Valise|Connaissances acquises',2],['BAIGNER','x',1],
['BAMBOU','Tige creuse d’Asie|Le panda le mange',2],['BANANE','x',1],
['BARBEAU','x',3],['BASCULE','Balance|Jeu de la balançoire',3],
['BATTRE','Frapper|Vaincre|Mélanger les œufs',1],['BEIGNET','x',2],
['BERGER','Il garde le troupeau|Chien de troupeau',2],['BIJOUX','Parures précieuses|Bagues et colliers',1],
['BISCUIT','x',2],['BLESSE','Il a mal|Il est atteint',2],
['BOUCLE','Elle attache la ceinture|Cheveu frisé|Répétition',2],['BOUGIE','Elle éclaire le gâteau|Cire à mèche',1],
['BOULES','Sphères|Jeu de pétanque',1],['BRANCHE','x',1],
['BRIQUE','Bloc de terre cuite|Elle bâtit le mur',1],['BRONZE','Alliage du sculpteur|Médaille de troisième',2],
['BROSSE','Elle nettoie|Coupe de cheveux courte',1],['BRUYERE','x',3],
['BUISSON','x',2],['CACHER','Dissimuler|Masquer',1],
['CAISSE','Boîte|On y paie|Instrument à percussion',1],['CALCUL','Opération de maths|Pierre du rein',2],
['CAMERA','Elle filme|Œil du cinéma',1],['CANAPE','Siège à plusieurs places|Petit toast',1],
['CANIF','x',3],['CAPOTE','Toit de la décapotable|Manteau militaire',3],
['CARAFE','Récipient à eau|Elle se pose sur la table',2],['CARESSE','x',2],
['CASIER','x',2],['CASQUE','Il protège la tête|Écouteurs',1],
['CEDILLE','x',3],['CENDRE','Résidu du feu|Poussière grise',2],
['CERCLE','Rond parfait|Groupe fermé',1],['CHAINE','Suite d’anneaux|Télévision|Montagne',1],
['CHALET','Maison de montagne|Bois et toit pentu',2],['CHARME','Séduction|Arbre des haies',2],
['CHIFFRE','x',1],['CHORALE','x',2],['CIBOULE','x',3],
['CIGALE','Elle chante en Provence|Insecte de l’été',2],['CIMENT','Il lie les briques|Poudre grise',2],
['CINEMA','Salle des films|Septième art',1],['CIRQUE','x',1],
['CLOCHE','Elle sonne au clocher|Couvercle de cuisine',1],['COLERE','Grande fâcherie|Emportement',1],
['COLLET','Piège à lapin|Col du vêtement',3],['COMBAT','Bagarre|Lutte',1],
['COMETE','Astre à longue traîne|Elle passe rarement',2],['COMPAS','Il trace les cercles|Instrument marin',2],
['CONFIT','Cuit dans sa graisse|Spécialité du Sud-Ouest',3],['COQUES','Enveloppes dures|Coquillages',2],
['CORAIL','Il bâtit les récifs|Rouge orangé',2],['CORBEAU','x',2],
['CORNET','Cône de glace|Petit sac de papier',2],['COUDRE','Assembler au fil|Travail de couturière',2],
['COURSE','On la gagne à l’arrivée|Achat rapide',1],['CRABES','Crustacés à pinces',1],
['CRAYON','x',1],['CREUSER','x',1],['CRINIERE','x',2],
['CRUCHE','Pot à anse|Personne un peu sotte',3],['CUISSE','x',2],
['CULOTTE','x',2],['CYCLONE','x',3],['DEBOUT','Sur ses pieds|Vertical',1],
['DECHET','Ce qu’on jette|Ordure',2],['DECIDE','Il a choisi|Résolu',1],
['DEDANS','À l’intérieur|Au-dedans',1],['DEGATS','Dommages|Casse',2],
['DEMAIN','Le jour d’après|Bientôt',1],['DENTELLE','x',2],
['DESERT','Étendue de sable|Vide de monde',1],['DESSUS','Au-dessus|Le haut',1],
['DETAIL','Petit élément|Vente au particulier',1],['DEVOIR','Travail scolaire|Obligation',1],
['DIABLE','Esprit du mal|Chariot à deux roues',2],['DIRECT','Sans détour|En temps réel',1],
['DIVERS','Variés|Différents',2],['DOSSIER','x',1],
['DOUANE','Contrôle à la frontière|Service des taxes',3],['DOUZE','x',1],
['DRAGON','x',2],['DRAPEAU','x',1],['ECHECS','Jeu du roi et de la reine|Insuccès',2],
['ECLUSE','Elle règle le niveau du canal|Sas des péniches',3],['ECORCE','Peau de l’arbre|Enveloppe du fruit',2],
['ECRIRE','Poser des mots|Rédiger',1],['ECURIE','Maison du cheval|Équipe de course',2],
['EGLISE','Bâtiment du culte|Elle a un clocher',1],['ELEVER','Faire monter|Éduquer',1],
['EMPIRE','Grand État|Domination',2],['ENCLOS','Terrain fermé|Parc à moutons',3],
['ENIGME','Devinette|Mystère',2],['ENTREE','Porte d’accès|Premier plat',1],
['EPAULE','x',1],['EPICES','Poivre et cannelle|Elles relèvent le plat',1],
['EPONGE','Elle absorbe l’eau|Animal marin',1],['ESPACE','Le cosmos|Intervalle',1],
['ESPOIR','Attente confiante|Espérance',1],['ETABLI','Table de l’atelier|Installé',3],
['ETOFFE','Tissu|Qualité d’une personne',2],['ETRIER','Support du pied du cavalier|Petit os de l’oreille',3],
['EVIDENCE','x',2],['FACTURE','x',2],['FAMILLE','x',1],
['FANION','Petit drapeau|Emblème d’équipe',3],['FARINE','Poudre du pain|Blé moulu',1],
['FAUCON','Rapide rapace|Oiseau de chasse',2],['FENDRE','Couper en deux|Ouvrir en long',2],
['FERMIER','x',1],['FEUILLE','x',1],['FICELLE','x',2],
['FIERTE','Sentiment d’honneur|Orgueil légitime',2],['FIGURE','Visage|Forme géométrique',1],
['FILETS','Ils prennent les poissons|Morceaux de viande',2],['FLECHE','Elle sort de l’arc|Pointe du clocher',1],
['FLOTTE','Ensemble de navires|Elle surnage',2],['FORGER','Travailler le métal chaud|Inventer',3],
['FOSSES','Trous creusés|Tranchées',2],['FOULARD','x',2],
['FRAISE','x',1],['FRELON','Grosse guêpe|Insecte redouté',3],
['FUMIER','Engrais de la ferme|Paille souillée',3],['GALERIE','x',2],
['GAMBAS','x',3],['GAZELLE','x',2],['GENIAL','Formidable|Digne d’un génie',1],
['GIBIER','Animal de chasse|Sanglier ou faisan',2],['GLISSE','Sport de neige|Elle dérape',2],
['GOELAND','x',2],['GOUTTE','Petite quantité d’eau|Maladie articulaire',1],
['GRAINS','Semences|Averse brève',2],['GRELON','Bille de glace|Il tombe de l’orage',3],
['GUEPE','Insecte rayé qui pique|Taille fine',2],['GUICHET','x',2],
['HABITS','Vêtements|Tenue',1],['HAMEAU','x',3],
['HARPON','Arme du pêcheur|Il perce le poisson',3],['HAUTES','Élevées|De grande taille',1],
['HERBES','Végétaux du pré|Fines, en cuisine',1],['HERISSON','x',2],
['HOTESSE','x',2],['HUITRE','Coquillage de Noël|Elle produit la perle',2],
['HUMEUR','x',2],['IMAGES','x',1],['INSTANT','x',1],
['JACHERE','x',3],['JAUNIR','x',2],['JETONS','Pièces de jeu|Marques',2],
['JOURNAL','x',2],['JOYAUX','Bijoux précieux|Trésors',3],
['JUMEAU','x',2],['JUNGLE','Forêt tropicale|Loi du plus fort',1],
['LACETS','Ils ferment les chaussures|Virages de la route',2],['LAMPES','Elles éclairent|Luminaires',1],
['LANGUE','Elle goûte|Français ou anglais',1],['LANTERNE','x',3],
['LAURIER','x',2],['LESSIVE','x',1],['LEVIER','Barre qui soulève|Moyen d’action',2],
['LIERRE','Plante grimpante|Il couvre les murs',2],['LIMACE','Escargot sans coquille|Lente',2],
['LINGOT','Barre d’or|Lingot de métal',3],['LOUTRE','x',2],
['LUMIERE','x',2],['LUNETTE','x',1],['MACHER','x',1],
['MAGRET','Filet de canard|Spécialité du Sud-Ouest',3],['MAILLE','Boucle du tricot|Trou du filet',2],
['MANCHE','Partie du vêtement|Poignée|Partie de jeu',1],['MANDAT','Pouvoir donné|Ordre de paiement',3],
['MANEGE','Tour de la fête foraine|Piste des chevaux',1],['MANOIR','Petit château|Demeure ancienne',2],
['MARAIS','Terrain d’eau stagnante|Marécage',2],['MARBRE','Pierre polie|Matière du sculpteur',2],
['MARINE','Flotte de guerre|Bleu foncé',1],['MASQUE','Il cache le visage|Protection',1],
['MATURE','Arrivé à maturité|Adulte',3],['MEDAILLE','x',1],
['MELEZE','Conifère des montagnes|Il perd ses aiguilles',3],['MENAGE','Entretien de la maison|Couple',1],
['MENTHE','Herbe fraîche|Parfum du sirop vert',1],['MEUBLE','Table ou armoire|Il garnit la pièce',1],
['MIETTE','Petit morceau de pain|Bribe',2],['MILIEU','Le centre|Environnement',1],
['MINUIT','Douze heures du soir|Fin du jour',1],['MODELE','Exemple à suivre|Il pose pour le peintre',1],
['MOELLE','Intérieur de l’os|Cœur de la plante',3],['MOMENT','Instant|Période',1],
['MONNAIE','x',1],['MORALE','Leçon de la fable|Règles du bien',2],
['MOTEUR','Il fait avancer|Force d’entraînement',1],['MOUCHE','Insecte agaçant|Centre de la cible',1],
['MOULIN','Il moud le grain|Ses ailes tournent',1],['MOUSSE','Bulles du savon|Plante des sous-bois|Jeune marin',1],
['MUSCLE','x',2],['NAPPES','Elles couvrent les tables|Étendues d’eau',2],
['NAVETTE','x',2],['NECTAR','Suc des fleurs|Boisson délicieuse',3],
['NEVEUX','Fils du frère|Ils ont un oncle',2],['NOMBRIL','x',2],
['NOTAIRE','x',3],['NOUILLE','x',1],['NOYAUX','Cœurs durs des fruits|Centres',2],
['NUAGES','x',1],['OASIS','x',2],['OBJETS','Choses|Buts visés',1],
['OCTAVE','Intervalle musical|Huit notes',3],['ODEURS','Parfums|Senteurs',1],
['OFFICE','Bureau|Service religieux',3],['OISEAU','x',1],
['OMBRES','Zones sans lumière|Silhouettes',1],['ONCLES','Frères du père',1],
['ORAGES','Tempêtes|Éclairs et tonnerre',1],['ORDURE','Déchet|Saleté',2],
['OREILLE','x',2],['ORFEVRE','x',3],['OSSATURE','x',3],
['OURSIN','Boule à piquants de la mer|Il vit sur les rochers',3],['OUTILS','x',1],
['PALAIS','Demeure royale|Voûte de la bouche',2],['PANIER','x',1],
['PANTIN','Marionnette|Personne influençable',3],['PARDON','Excuse accordée|Fête bretonne',2],
['PARFUM','Odeur agréable|Flacon de senteur',1],['PARLER','Dire des mots|Converser',1],
['PATATE','Pomme de terre|Grande forme, familièrement',1],['PATURE','Herbe des bêtes|Pré de pâturage',3],
['PAVOIS','Ensemble des pavillons|Bouclier ancien',3],['PECHER','Arbre à pêches|Aller à la pêche',1],
['PEDALE','Elle fait tourner le vélo|Commande au pied',1],['PEIGNE','Il coiffe|Il démêle',1],
['PELAGE','Poil de l’animal|Fourrure',3],['PELOTE','Boule de laine|Jeu basque',2],
['PENSEE','Idée|Fleur du jardin',1],['PERLES','Bijoux de l’huître|Erreurs amusantes',2],
['PETALE','Feuille de la fleur|Élément de la corolle',2],['PHOQUE','Mammifère des banquises|Il nage et glisse',1],
['PIERRE','Caillou|Matière du mur',1],['PIGEON','Oiseau des villes|Personne naïve',1],
['PILIER','Colonne de soutien|Il soutient l’édifice',2],['PINCEAU','x',1],
['PIRATE','Bandit des mers|Il copie illégalement',1],['PISCINE','x',1],
['PLACARD','x',1],['PLAINE','Étendue plate|Terrain sans relief',1],
['PLANTE','x',1],['PLATRE','Poudre blanche du mur|Il immobilise le bras',2],
['PLUMES','Elles couvrent l’oiseau|Elles servaient à écrire',1],['POIGNE','Force de la main|Autorité',3],
['POIVRE','Épice noire|Il pique la langue',1],['POMMIER','x',1],
['PORTAIL','x',2],['POTAGE','Soupe|Bouillon',2],
['POUCES','Doigts courts|Mesures anglaises',2],['POUDRE','Fine poussière|Explosif ancien',1],
['POULET','Volaille rôtie|Jeune coq',1],['POUSSE','Jeune tige|Il appuie dessus',2],
['PRAIRIE','x',3],['PRENOM','x',1],['PRINCE','x',1],
['PROJET','Ce qu’on prévoit|Plan à réaliser',1],['PRUNES','Fruits violets|Amendes, familièrement',1],
['PUZZLE','Jeu de pièces à assembler|Casse-tête',1],['QUILLE','Elle tombe à la boule|Bas du bateau',2],
['RABOT','x',3],['RACINE','x',1],['RADEAU','Assemblage flottant|Barque de fortune',2],
['RAISIN','Fruit de la vigne|Il fait le vin',1],['RAMEAU','Petite branche|Dimanche avant Pâques',3],
['RAPIDE','Très vite|Torrent de rivière',1],['RATEAU','Il ramasse les feuilles|Outil du jardinier',1],
['RAVIN','Vallée étroite et profonde|Fossé naturel',3],['RECIFS','Rochers sous la mer|Dangers du large',3],
['REFUGE','Abri en montagne|Protection',2],['REGARD','Coup d’œil|Ouverture d’égout',1],
['REGLES','Lois|Instruments à tracer',1],['REINES','Épouses des rois|Cartes de jeu',1],
['REPOSE','Il se détend|Il est posé',1],['RESEAU','Ensemble connecté|Toile de relations',1],
['RESUME','Version courte|Synthèse',2],['RETARD','Il arrive trop tard|Décalage',1],
['REUSSITE','x',2],['REVEIL','Il sonne le matin|Retour à la conscience',1],
['RICHES','Ils ont de l’argent|Fortunés',1],['RIVAGE','x',2],
['ROBINET','x',1],['ROCHER','Grosse pierre|Bonbon au chocolat',1],
['ROSEAU','Plante des marais|Tige creuse',2],['ROTULE','Os du genou|Petite roue',3],
['ROUAGE','Pièce d’engrenage|Élément du système',3],['ROUTES','Voies goudronnées|Chemins',1],
['RUCHER','Ensemble de ruches|Domaine de l’apiculteur',3],['RUELLE','Petite rue|Passage étroit',2],
['SABOTS','Chaussures de bois|Pieds du cheval',2],['SACHET','Petit sac|Il contient le thé',1],
['SAISON','Été ou hiver|Période de l’année',1],['SALADE','Verte, dans l’assiette|Mélange|Histoire inventée',1],
['SANDALE','x',2],['SANGLIER','x',3],['SAPINS','Arbres de Noël|Conifères',1],
['SARDINE','x',3],['SAUCES','Elles nappent les plats|Jus liés',1],
['SAVANE','x',2],['SAVANT','Il sait beaucoup|Scientifique',2],
['SCEAU','x',3],['SEIGLE','Céréale du pain noir|Farine foncée',3],
['SEMELLE','Dessous de la chaussure|Elle use le sol',2],['SENTIER','x',1],
['SERPENT','x',1],['SERVICE','x',1],['SIESTE','x',1],
['SIGNAL','Signe convenu|Alerte',2],['SILLON','Trace de la charrue|Rainure du disque',3],
['SIROPS','Boissons sucrées|Médicaments liquides',1],['SOCLE','Base de la statue|Support',2],
['SOMMET','Point le plus haut|Réunion des chefs',1],['SORTIE','Porte pour partir|Publication',1],
['SOUPES','Potages|Bouillons',1],['SOURCE','Départ de la rivière|Origine',1],
['SOUTIEN','x',2],['SPHERE','Boule parfaite|Domaine d’activité',2],
['SPIRALE','x',2],['STATUE','Sculpture debout|Figure de pierre',1],
['SUCETTE','x',1],['SUCRES','Douceurs|Glucides',1],
['SURSAUT','x',3],['TABLEAU','x',1],['TALENT','Don naturel|Aptitude',1],
['TAMPON','Il imprime le cachet|Amortisseur',2],['TAUREAU','x',1],
['TEMOIN','Il a vu la scène|Bâton du relais',2],['TEMPLE','Édifice sacré|Lieu de culte',2],
['TERRAIN','x',1],['TERRIER','x',2],['TICKET','Billet d’entrée|Reçu',1],
['TIGES','Elles portent les fleurs|Tiges de métal',2],['TIMBRE','Il affranchit la lettre|Son de la voix',2],
['TISANE','Infusion de plantes|Boisson du soir',1],['TISSER','Croiser les fils|Fabriquer la toile',2],
['TOMATE','x',1],['TONNEAU','x',2],['TORRENT','x',2],
['TOUCHE','Elle est du clavier|Contact léger|Ligne du terrain',1],['TOURNER','x',1],
['TRACER','Dessiner une ligne|Marquer le chemin',1],['TRAINEAU','x',2],
['TRAJET','Chemin parcouru|Parcours',1],['TREFLE','Herbe à trois feuilles|Couleur des cartes',1],
['TRESSE','Cheveux entrelacés|Natte',2],['TRIBUNE','x',2],
['TROMPE','Nez de l’éléphant|Instrument de chasse|Il ment',1],['TROUPE','Groupe d’acteurs|Bande de soldats',2],
['TRUELLE','x',3],['TULIPE','Fleur de Hollande|Bulbe du printemps',1],
['TUNNEL','x',1],['TURBAN','Coiffe enroulée|Étoffe autour de la tête',3],
['UNIQUE','x',2],['USINES','x',1],['VAGUES','Elles viennent de la mer|Imprécises',1],
['VALEUR','Prix|Courage|Importance',1],['VALLEE','Creux entre les montagnes|Elle suit la rivière',1],
['VAPEUR','Eau évaporée|Elle fait tourner la machine',2],['VELOURS','x',2],
['VENDRE','Céder contre argent|Commercer',1],['VERGER','x',2],
['VERNIS','Couche brillante|Il protège le bois',2],['VERSER','Faire couler|Payer',1],
['VESTON','Veste d’homme|Haut du costume',3],['VIANDE','Chair de boucherie|Steak ou rôti',1],
['VICTOIRE','x',1],['VIOLET','Couleur du prunier|Entre bleu et rouge',1],
['VIRAGE','Tournant de la route|Changement de cap',1],['VITRINE','x',1],
['VOILES','Elles poussent le bateau|Tissus qui cachent',1],['VOISIN','x',1],
['VOLANT','Il dirige la voiture|Il vole au badminton',1],['VOYANT','Il prédit l’avenir|Lumière d’alerte|Très visible',2],
].filter(w => w[1] !== 'x');

const X7 = [
['ABRICOT','Fruit orange à noyau|Il mûrit en été',2],['ACCUEIL','Réception|Bienvenue',2],
['ADRESSE','Où l’on habite|Habileté',2],['AFFAIRE','Marché conclu|Dossier judiciaire',2],
['AIGUILLE','x',2],['AMPOULE','Elle éclaire|Cloque au pied',1],
['ANCIENS','Ceux d’avant|Anciens élèves',2],['ANNEAUX','Agrès de gymnastique|Bagues',2],
['ARDOISE','Pierre du toit|Compte du café',2],['ARGENTE','Couleur de l’argent|Métallisé',3],
['ARMOIRE','Grand meuble à portes|Elle range le linge',1],['ARROSER','Donner de l’eau aux plantes|Fêter dignement',1],
['ATELIER','Lieu de travail manuel|Cours pratique',2],['ATTAQUE','Assaut|Début vif',2],
['AUBERGE','Petit hôtel de campagne|Relais des voyageurs',2],['AUTOMNE','x',1],
['AVALANCHE','x',2],['AVENUE','x',1],['BAIGNADE','x',2],
['BALEINE','Géante des mers|Elle souffle',1],['BALLADE','Promenade|Poème chanté',2],
['BAMBINS','Petits enfants|Bouts de chou',2],['BANDEAU','Il couvre les yeux|Ruban de tête',2],
['BANQUISE','x',2],['BATAILLE','x',2],['BERCEAU','Lit du bébé|Origine',2],
['BIJOUTIER','x',3],['BOUCHON','Il ferme la bouteille|Embouteillage',1],
['BOUQUET','Assemblage de fleurs|Final du feu d’artifice',1],['BOUSSOLE','x',2],
['BRIQUET','Il fait du feu|Allume-cigare',2],['BROCHET','Poisson carnassier|Il vit en rivière',3],
['BRODERIE','x',3],['BRULURE','Marque du feu|Douleur cuisante',2],
['CABANON','Petite cabane|Abri de jardin',3],['CABINET','Bureau du médecin|Petit meuble',2],
['CALCAIRE','x',3],['CALMANT','Il apaise|Médicament tranquillisant',3],
['CAMEMBERT','x',2],['CANNELLE','x',2],['CAPITAINE','x',2],
['CARAVANE','x',2],['CARESSE','Geste tendre|Effleurement',2],
['CAROTTE','Légume orange|Elle rend aimable, dit-on',1],['CASCADE','Chute d’eau|Suite rapide',2],
['CASSEROLE','x',1],['CEINTURE','x',1],['CERVEAU','Organe de la pensée|Meneur d’un plan',1],
['CHACUNE','Toutes, une par une|Chaque femme',2],['CHALEUR','Température élevée|Cordialité',1],
['CHAMBRE','Pièce du lit|Assemblée',1],['CHANTIER','x',2],
['CHAPEAU','Il couvre la tête|Bravo !',1],['CHARBON','Combustible noir|Il chauffait les trains',2],
['CHARIOT','Petit chariot de courses|Il roule',2],['CHARRUE','Elle laboure|Outil du paysan',3],
['CHASSEUR','x',2],['CHAUSSON','x',2],['CHEMISE','x',2],
['CHENILLE','x',2],['CHEVEUX','Ils poussent sur la tête|On les coiffe',1],
['CHIFFRE','Nombre écrit|Montant des ventes',1],['CHORALE','Groupe de chanteurs|Chœur amateur',2],
['CHUCHOTE','x',3],['CIGOGNE','Grand oiseau blanc|Elle niche sur les toits',2],
['CISEAUX','Ils coupent le papier|Outil à deux lames',1],['CITRON','Agrume jaune et acide|Il parfume le thé',1],
['CLAVIER','x',2],['CLOCHER','Tour de l’église|Il abrite les cloches',2],
['COIFFURE','x',1],['COLLIER','Bijou du cou|Il tient le chien',1],
['COLLINE','x',2],['COMPOTE','Fruits cuits|Dessert des enfants',2],
['CONCERT','Spectacle de musique|Représentation live',1],['CONFORT','Bien-être|Aisance',2],
['CONSEIL','Avis donné|Assemblée qui décide',1],['CORBEAU','Oiseau noir|Il croasse',2],
['CORNICHE','x',3],['COSTUME','Habit complet|Déguisement',1],
['COURAGE','Bravoure|Force morale',1],['COURONNE','x',1],
['COUSSIN','Il rembourre le canapé|Il repose la tête',1],['COUTURE','Art de l’aiguille|Ligne cousue',2],
['CRINIERE','Poils du cou du lion|Chevelure abondante',2],['CRISTAL','Verre très pur|Il sonne clair',2],
['CROISSANT','x',1],['CUILLERE','x',1],['CULOTTE','Sous-vêtement|Pantalon court',2],
['CYCLONE','Tempête tournante|Ouragan',3],['DANSEUR','Il évolue sur scène|Il tourne en rythme',1],
['DAUPHIN','Mammifère marin joueur|Successeur du roi',1],['DECHIRE','Mis en pièces|Fendu',2],
['DECOUPE','Il taille des formes|Silhouette découpée',2],['DEGUISE','Costumé|Masqué',2],
['DENTIER','Dents amovibles|Prothèse dentaire',3],['DENTELLE','x',2],
['DESSERT','x',2],['DESSINE','Il croque au crayon|Tracé',1],
['DIAMANT','x',2],['DIPLOME','Papier de réussite|Titre obtenu',2],
['DOSSIER','Ensemble de documents|Dos de la chaise',1],['DRAPEAU','Emblème du pays|Il flotte au vent',1],
['ECHARPE','Elle protège le cou|Insigne du maire',1],['ECLIPSE','Le soleil disparaît|Absence passagère',2],
['ECRITURE','x',1],['ECUREUIL','x',1],['ELEPHANT','x',1],
['EMBALLE','Enveloppé|Enthousiasmé',2],['ENCLUME','Le forgeron y frappe|Os de l’oreille',3],
['ENERGIE','Force disponible|Électricité',1],['ENVELOPPE','x',1],
['EPICERIE','x',2],['EPINGLE','Elle pique le tissu|Elle attache',2],
['ERABLE','x',2],['ESCARGOT','x',1],['ESSENCE','Carburant|Nature profonde',2],
['ETAGERE','x',3],['ETINCELLE','x',2],['ETRANGE','Bizarre|Curieux',2],
['EVENTAIL','x',3],['EVIDENCE','Chose claire|Certitude',2],
['FACTURE','Note à payer|Manière de faire',2],['FALAISE','x',3],
['FAMILLE','Parents et enfants|Groupe apparenté',1],['FANTOME','Revenant|Apparition',1],
['FAUTEUIL','x',2],['FENOUIL','Légume anisé|Bulbe parfumé',3],
['FERMIER','Il exploite la ferme|Paysan',1],['FESTIVAL','x',1],
['FEUILLE','Elle pousse sur l’arbre|Page de papier',1],['FICELLE','Petite corde|Ruse',2],
['FIGURINE','x',2],['FLAMBEAU','x',3],['FOUGERE','Plante des sous-bois|Elle a des frondes',3],
['FOULARD','Carré de soie|Il orne le cou',2],['FOURMIS','Insectes travailleurs|Picotements',1],
['FRAICHE','Un peu froide|Récente',1],['FRAMBOISE','x',1],
['FROMAGE','x',2],['FRONTIERE','x',2],['GALERIE','Passage couvert|Salle d’exposition',2],
['GARNITURE','x',2],['GAZELLE','Antilope rapide|Elle bondit',2],
['GENIALE','Formidable|Digne d’un génie',1],['GENOUX','Articulations des jambes|On s’y agenouille',1],
['GIROFLE','Clou parfumé|Épice piquante',3],['GLACIER','x',3],
['GOELAND','Grand oiseau des ports|Cousin de la mouette',2],['GOULOTTE','x',3],
['GOURMAND','x',1],['GRANITE','Roche dure des montagnes|Pierre de Bretagne',3],
['GRAPPES','Assemblages de raisins|Ensembles serrés',2],['GRENIER','x',3],
['GRIFFES','Ongles du chat|Marques de créateur',2],['GUICHET','Comptoir de vente|Ouverture de service',2],
['GUIRLANDE','x',2],['GUITARE','x',1],['HAMEAUX','Tout petits villages',3],
['HARICOT','x',2],['HAUTEUR','x',3],['HERISSON','Il a des piquants|Il se roule en boule',2],
['HISTOIRE','x',2],['HOMARDS','x',3],['HORIZON','Ligne du lointain|Perspective',2],
['HORLOGE','x',2],['HOTESSE','Elle accueille|Elle sert en vol',2],
['HUITRES','Coquillages de fête|Elles se dégustent crues',2],['IMMENSE','x',3],
['INCENDIE','x',2],['INSECTE','x',2],['INSTANT','Moment très bref|Seconde',1],
['JACINTHE','x',3],['JARDINS','x',2],['JOURNAL','x',2],
['JUMELLES','Elles rapprochent le lointain|Sœurs nées ensemble',2],['LABYRINTHE','x',3],
['LANTERNE','Lampe portative|Feu arrière du véhicule',3],['LAURIER','Feuille du pot-au-feu|Gloire du vainqueur',2],
['LESSIVE','Poudre à laver|Corvée du linge',1],['LEZARDS','x',3],
['LIBERTE','x',2],['LIMONADE','x',2],['LOTERIE','x',3],
['LUMIERE','x',2],['LUNETTE','Verre optique|Instrument d’observation',1],
['MACHINE','x',2],['MAGASIN','Boutique|Réserve à munitions',1],
['MANTEAU','x',1],['MARQUEUR','x',2],['MARTEAU','x',2],
['MATELAS','Il garnit le lit|Couche moelleuse',1],['MEDAILLE','Récompense du sportif|Disque gravé',1],
['MELODIE','x',2],['MENUISIER','x',2],['MERVEILLE','x',2],
['MESANGE','Petit oiseau du jardin|Elle vient au nichoir',3],['MIRACLE','Fait extraordinaire|Prodige',2],
['MOISSON','Récolte du blé|Grande cueillette',2],['MONNAIE','Pièces et billets|Ce qu’on rend',1],
['MONTAGNE','x',1],['MOUCHOIR','x',1],['MOUSTACHE','x',1],
['MOUTARDE','x',1],['MUGUET','x',2],['MUSIQUE','x',2],
['NAVETTE','Va-et-vient régulier|Engin spatial',2],['NECTARS','x',3],
['NOISETTE','x',2],['NOUILLE','Pâte longue|Personne un peu molle',1],
['NOUVEAU','x',2],['NUMEROS','x',2],['OCTOBRE','x',2],
['OMELETTE','x',2],['ORANGER','x',3],['ORCHIDEE','x',3],
['OREILLE','x',2],['OUVRAGE','x',3],['PALETTE','Plateau du peintre|Gamme de choix',2],
['PANIERS','x',1],['PANTHERE','x',2],['PAPILLON','x',1],
['PARASOL','x',1],['PARFUMS','Senteurs|Fragrances',1],
['PATIENCE','x',2],['PEINTRE','x',2],['PEINTURE','Art des couleurs|Elle couvre le mur',2],
['PELICAN','Oiseau à grande poche|Pêcheur des lagunes',3],['PENDULE','Horloge à balancier|Elle oscille',2],
['PEPINS','Graines de la pomme|Ennuis, familièrement',2],['PERROQUET','x',1],
['PIGEONS','Oiseaux des places|Naïfs, familièrement',1],['PINCEAU','Outil du peintre|Il étale la couleur',1],
['PIRATES','x',2],['PISCINE','Bassin de nage|On y plonge',1],
['PLACARD','Rangement mural|Affiche',1],['PLANCHE','Morceau de bois plat|Illustration',1],
['PLATANE','Arbre des allées|Son écorce pèle',3],['POIREAU','x',1],
['POISSON','x',1],['POMMIER','Arbre à pommes|Il fleurit au printemps',1],
['PORTAIL','Grande porte|Page d’accueil web',2],['POTAGER','x',3],
['POUSSIN','Bébé de la poule|Il sort de l’œuf',1],['PRAIRIE','x',3],
['PRENOM','x',1],['PRESSION','x',2],['PRINTEMPS','x',1],
['PROBLEME','x',1],['PUZZLES','Jeux à assembler|Casse-tête',1],
['RACINES','x',1],['RADIATEUR','x',2],['RAQUETTE','x',1],
['RECETTE','Manière de cuisiner|Argent encaissé',1],['RECOLTE','x',3],
['REGLAGE','x',2],['REPTILE','x',2],['RESSORT','Il rebondit|Compétence d’un tribunal',2],
['REUSSITE','Succès|Jeu de cartes solitaire',2],['RIVIERE','x',2],
['ROBINET','Il donne l’eau|On l’ouvre et le ferme',1],['ROSEAUX','Plantes des marais|Tiges creuses',2],
['ROULEAU','x',3],['ROYAUME','Pays du roi|Domaine',1],
['RUISSEAU','x',1],['SANDALE','Chaussure ouverte|Chaussure d’été',2],
['SANGLIER','x',3],['SARDINE','x',3],['SAUMON','x',1],
['SEMAINE','x',2],['SENTIER','Petit chemin|Piste de randonnée',1],
['SERPENT','Reptile qui rampe|Il siffle',1],['SERVICE','Aide rendue|Au tennis|Département',1],
['SIESTE','Somme de l’après-midi|Repos court',1],['SILENCE','x',2],
['SOLDATS','Militaires|Figurines de plomb',1],['SOMMEIL','Repos de la nuit|Envie de dormir',1],
['SORCIER','Il jette des sorts|Magicien des contes',1],['SOUCOUPE','x',2],
['SOURIRE','x',2],['SOUTIEN','Aide apportée|Appui',2],
['SPECTACLE','x',1],['SPIRALE','Courbe qui s’enroule|Escalier en colimaçon',2],
['SUCETTE','Bonbon sur bâton|Friandise des enfants',1],['SURSAUT','Réaction brusque|Sursis d’énergie',3],
['TABLEAU','Œuvre peinte|Panneau de la classe',1],['TAUREAU','Mâle de la vache|Signe du zodiaque',1],
['TEMPETE','Vent très fort|Grande agitation',1],['TERRAIN','Espace de jeu|Parcelle de sol',1],
['TERRIER','Trou du lapin|Chien fouisseur',2],['THEATRE','x',2],
['TIROIRS','Compartiments du meuble|Ils coulissent',1],['TOITURE','x',3],
['TONNEAU','Fût de bois|Tonneau de vin',2],['TORRENT','Cours d’eau rapide|Flot impétueux',2],
['TORTUES','x',2],['TOURNER','Faire un tour|Filmer',1],
['TRACTEUR','x',1],['TRAINEAU','Véhicule de neige|Celui du Père Noël',2],
['TRAJETS','x',3],['TRIANGLE','x',1],['TRIBUNE','Estrade de l’orateur|Gradin du stade',2],
['TROMPETTE','x',2],['TROTTOIR','x',1],['TRUFFES','Champignons rares|Chocolats ronds',3],
['UNIVERS','x',2],['URGENCE','x',3],['VACANCES','x',1],
['VAISSEAU','x',2],['VELOURS','Tissu doux|Étoffe soyeuse',2],
['VENDEUR','Il tient le magasin|Il propose des articles',1],['VENDREDI','x',1],
['VERGERS','x',3],['VILLAGE','x',2],['VIOLETTE','x',2],
['VITRINE','Devanture du magasin|Meuble vitré',1],['VOITURE','x',2],
['VOYAGES','x',2],['ZEBRURE','Rayure|Marque en zigzag',3],
].filter(w => w[1] !== 'x');

const X8 = [
['ABRICOTS','Fruits orangés à noyau',2],['ARROSOIR','Il abreuve les plantes|Récipient à pomme',2],
['AVALANCHE','x',2],['BAIGNADE','Bain en plein air|Plaisir de l’été',2],
['BALANCOIRE','x',1],['BANQUISE','Glace de la mer polaire|Terrain de l’ours blanc',2],
['BATAILLE','Combat|Jeu de cartes',2],['BOUSSOLE','Elle indique le nord|Instrument d’orientation',2],
['BROUILLARD','x',2],['CALENDRIER','x',1],['CAMEMBERT','Fromage normand|Graphique circulaire',2],
['CANNELLE','Épice en bâton|Parfum du gâteau',2],['CAPITAINE','Chef du navire|Grade militaire',2],
['CARAVANE','Remorque de vacances|File de chameaux',2],['CASSEROLE','Elle chauffe sur le feu|Récipient à queue',1],
['CEINTURE','Elle tient le pantalon|Elle sécurise en voiture',1],['CHANTIER','Lieu de construction|Grand désordre',2],
['CHASSEUR','Il traque le gibier|Avion de combat',2],['CHAUSSON','Pantoufle|Pâtisserie aux pommes',2],
['CHENILLE','Future papillon|Bande du char',2],['COIFFURE','Manière de porter ses cheveux|Chapeau',1],
['COURONNE','Elle ceint la tête du roi|Cercle de fleurs',1],['CROISSANT','Viennoiserie du matin|Forme de la lune',1],
['ECRITURE','Tracé des lettres|Style de l’auteur',1],['ECUREUIL','Rongeur à queue touffue|Il stocke les noisettes',1],
['ELEPHANT','Le plus gros terrestre|Il a une trompe',1],['ENVELOPPE','Elle contient la lettre|Elle recouvre',1],
['EPICERIE','Petit commerce alimentaire|Boutique du village',2],['ESCARGOT','Il porte sa coquille|Lent baveux',1],
['ETINCELLE','Petit éclat de feu|Début d’un incendie',2],['EVENTAIL','Il rafraîchit|Gamme de choix',3],
['FESTIVAL','Fête culturelle|Série de spectacles',1],['FIGURINE','Petite statuette|Jouet de collection',2],
['FLAMBEAU','Torche enflammée|Symbole transmis',3],['FRAMBOISE','Petit fruit rouge|Parfum du sirop',1],
['FRONTIERE','Limite entre pays|Barrière',2],['GARNITURE','Ce qui accompagne le plat|Ornement',2],
['GOURMAND','Il aime manger|Amateur de sucreries',1],['GUIRLANDE','Décoration du sapin|Chaîne lumineuse',2],
['JACINTHE','Fleur parfumée du printemps|Bulbe coloré',3],['LIMONADE','Boisson pétillante|Citronnade gazeuse',2],
['MARQUEUR','Feutre épais|Buteur du match',2],['MENUISIER','Il travaille le bois|Artisan des meubles',2],
['MERVEILLE','Chose splendide|Prodige',2],['MOUCHOIR','Il essuie le nez|Carré de tissu',1],
['MOUSTACHE','Poils sur la lèvre|Le chat en a',1],['MOUTARDE','Condiment jaune piquant|Spécialité de Dijon',1],
['PANTHERE','Grand félin tacheté|Fauve noir',2],['PARASOL','Il protège du soleil|Ombrelle de plage',1],
['PATIENCE','Vertu de qui attend|Jeu de cartes',2],['PERROQUET','Oiseau qui répète|Il a un bec crochu',1],
['POIREAU','Légume long et vert|On l’aime en vinaigrette',1],['PRESSION','Force exercée|Bouton qui se clipse',2],
['PRINTEMPS','Saison des fleurs|Après l’hiver',1],['PROBLEME','Difficulté|Exercice de maths',1],
['RADIATEUR','Il chauffe la pièce|Il refroidit le moteur',2],['RAQUETTE','Elle frappe la balle|Elle marche sur la neige',1],
['REPTILE','Serpent ou lézard|Animal à écailles',2],['RUISSEAU','Petit cours d’eau|Filet qui coule',1],
['SAUMON','Poisson rose|Il remonte les rivières',1],['SOUCOUPE','Petite assiette de la tasse|Volante, elle intrigue',2],
['SPECTACLE','Représentation|Vue étonnante',1],['TRACTEUR','Engin de la ferme|Il tire la remorque',1],
['TRIANGLE','Figure à trois côtés|Instrument à percussion',1],['TROMPETTE','Instrument à vent|Cuivre éclatant',2],
['TROTTOIR','Bord de la rue pour piétons|On y marche',1],['VAISSEAU','Grand navire|Engin spatial|Il conduit le sang',2],
['VIOLETTE','Petite fleur mauve|Parfum délicat',2],
].filter(w => w[1] !== 'x');

module.exports = { X4, X5, X6, X7, X8 };